### ISSUE TITLE
Chat bot doesn't respond if my account doesn't have payment details

### ISSUE THREAD

**Issue by Jackjones408** [MichelNivard/gptstudio#100]
Please briefly describe your problem and what output you expect.

Whenever I write a prompt in the command box the chatbot doesn't reply with any idea on how I can fix that
`

**Comment by calderonsamuel** [comment]
Please provide an example. It would be easier to help you if you provide:

1. The content of your prompt
2. The response you received

Have in mind that your prompt should include specific instructions on the task you expect the chatbot to accomplish

**Comment by lucky5sugar** [comment]
I have a same problem.
I sent an exactly same prompt as in the README.md and received no response.

This is my R environment.

> platform       aarch64-apple-darwin20      
> arch           aarch64                     
> os             darwin20                    
> system         aarch64, darwin20           
> status                                     
> major          4                           
> minor          2.1                         
> year           2022                        
> month          06                          
> day            23                          
> svn rev        82513                       
> language       R                           
> version.string R version 4.2.1 (2022-06-23)

![image](https://github.com/MichelNivard/gptstudio/assets/26211395/3de17513-d36d-4d67-883f-dc7bb88d1418)

**Comment by calderonsamuel** [comment]
Thank you for the report!

This looks like an error in the communication between the StreamHandler and the shiny session. Are you using the CRAN or the github version?

**Comment by lucky5sugar** [comment]
I used the following code and I think it is a CRAN version.
`install.packages("gptstudio")`

**Comment by efinlay** [comment]
I installed first by using install.packages, a second time from github. I provided my API code first by Sys.setenv(OPENAI_API_KEY = "<APIKEY>"), then starting ChatGPT from the addins menu and providing the key when prompted, then by finding the .Renviron file and adding the key to that. In all cases when I try to prompt for code all I see is the little robot icon, it has never responded.
![image](https://github.com/MichelNivard/gptstudio/assets/40832929/09697c7b-e9fe-4579-96fe-460777f0a9c1)
If I try to use comment your code I get an error that Open AI API request failed Error 429 too Many requests
![image](https://github.com/MichelNivard/gptstudio/assets/40832929/e6070e89-8604-4c91-878a-c267aa6a6616)

Is this an API issue? What else can I try?

**Comment by calderonsamuel** [comment]
As you can  see in the error message, you have error 429. The error is linking you to two websites where you can see more info on the errors. I think one of two things are happening: 

1. You didn't provide an API KEY (see the [prerequisites in the README](https://github.com/MichelNivard/gptstudio#prerequisites))
2. Your API quota has reached its limit (go to the sites linked in the error message)

Let us know if any of those fix your issue

**Comment by jadams125** [comment]
Hey all. I am getting the same errors, and I provided an API key. I do not think I had reached my quota, since I created a key for the first time to run this code and package.

**Comment by efinlay** [comment]
Mine was also a newly generated key. I signed in to OpenAI using Google to create the key and was never prompted to enter any payment details, are there different API keys for free and with the potential to pay?

**Comment by calderonsamuel** [comment]
@efinlay I guess if you dont provide payment details your quota would be 0 dolars/tokens, so that would explain the "Too many requests" error. Let me be totally explicit about this, you CAN'T use your openai api key without paying OpenAI for its usage. If you are afraid that it will cost you a lot of money to use it, it is possible to set rate limits in your OpenAI account settings. Also, since last week, the cost of using api keys for chat completions with the 3.5-turbo model (the default) has been reduced 25% .

Personally, the most I've been billed is around 2 dolars by a whole month, but of course it will depend on how you use it. Give it a try and check how much it costs you <https://platform.openai.com/account/usage>.

If all the reports on this thread have in common a lack of payment details in the OpenAI platform, we could consider this issue as closed. Let us know!

**Comment by efinlay** [comment]
Thank you very much, that sounds like it was the problem for me at least. I may come back and experiment with it myself in the future but I can't insist that a class of students create paying accounts, even if it does turn out to be minimal prices.
If I'm not the only one having the issue it might help to note in the instructions that it has to be a paying account API key for those of us who don't know enough about OpenAI to take that for granted and try with the free version.
Thanks again

**Comment by jadams125** [comment]
Thanks for the prompt help. This seems to be my issue as well.

**Comment by calderonsamuel** [comment]
Please @JamesHWade rename this issue to "Chat bot doesn't respond if my account doesn't have payment details". I think we can close this once we explicitly state in the README that, for now, there is no free tier for this addin.

**Comment by JamesHWade** [comment]
Readme updated with #109
