### ISSUE TITLE
Feature Request: Support inference api of HuggingFace or Local LLMs

### ISSUE THREAD

**Issue by M-Colley** [MichelNivard/gptstudio#105]
Hey there, this is a great package! Thank you so much for this work.

I was wondering whether additional support for other model types could help alleviate the financial burden of using OpenAI. There are numerous alternatives on HuggingFace which can be reached by their inference API. 

Additionally, some LLMs could be run locally, e.g. https://huggingface.co/declare-lab/flan-alpaca-gpt4-xl (requires 12 GB VRAM) if such a machine were available. Other models include https://huggingface.co/tiiuae/falcon-7b which can be used both academically and even commercially.

Kind regards

**Comment by JamesHWade** [comment]
Thank you for submitting this suggestion. It is absolutely something we should do.

Expanding to other models and APIs will require a decent bit of code refactoring, but it's inevitable. Here's a list of APIs we should consider including:

- [ ] [HuggingFace inference API](https://huggingface.co/inference-api)
- [ ] [Bard API](https://makersuite.google.com/app/home)
- [ ] [Anthropic's Claude API](https://console.anthropic.com/docs/api)
- [ ] [Azure OpenAI Service](https://azure.microsoft.com/en-us/products/cognitive-services/openai-service)

Local models would be fantastic. I've been playing with GPT4All's models, but thank you for suggesting some others.

I'd like to target this for our next CRAN release.

**Comment by MichelNivard** [comment]
@JamesHWade For local models can we coordinate on precise quantised model file-spec? I have an R specific model that just finished training that might be a very good candidate model (though this is pending formal evaluation). The instruction following  fine tuning is currently ~1 hours so I could easily adjust fine-tuning to an R/package specific Q&A prompt format (I have a reasonably standard "### Assistant: " and "### Human: " currently...).

**Comment by JamesHWade** [comment]
I have a start on the HuggingFace and an S3 method to make it easier to swap between services more easily. 

I'll upload what I have as a PR draft by the end of the day. It may be tricky with steaming for some but not all. But, I bet we can figure it out. 

Local models might be the hardest considering we likely have to use reticulate.

I'm excited! This will be fun!🚀

**Comment by MichelNivard** [comment]
I think we can use c++ libraries for quantized verfsion of local models, So process the model with one of the tools the qunatize them and speed them up (like: https://github.com/ggerganov/ggml or: https://github.com/ggerganov/llama.cpp and them talk to these from R using Rcpp? The current risk is that eco system hasn't solidified yet and we risk chasing the ever shifting standard...

**Comment by JamesHWade** [comment]
#109 Addresses HuggingFace, Bard, and Anthropic. Still to go: local models and Azure OpenAI

**Comment by MichelNivard** [comment]
Hi @JamesHWade I have a basic model ready I want trial on an Huggingface inference endpoint (https://huggingface.co/inference-endpoints) is this supported currently?

**Comment by JamesHWade** [comment]
Is that the same as the "Hosted Inference Endpoint" ([docs](https://huggingface.co/docs/api-inference/index)). It's not exactly clear to me. The hosted inference endpoint works in the current dev version (>= 0.2.0.9000).

**Comment by MichelNivard** [comment]
No it's the more mature production API they offer: https://huggingface.co/docs/inference-endpoints/index
