### ISSUE TITLE
Refactor to remove top_p?

### ISSUE THREAD

**Issue by JamesHWade** [MichelNivard/gptstudio#11]
I saw on OpenAI's documentation that they recommend setting `temperature` _or_ `top_p` but not both. Think we should remove `top_p` from the add-ins? I already did it for `{gpttools}` but thought I'd ask before doing it here.

**Comment by MichelNivard** [comment]
Sure sounds good, can always add back un (I think its always set to 1 so far)

**Comment by JamesHWade** [comment]
`top_p` removed with #14
