### ISSUE TITLE
! Recv failure: Connection reset by peer  

### ISSUE THREAD

**Issue by lizongzhang** [MichelNivard/gptstudio#112]
I need to access the ChatGPT website using a VPN. However, when I try to set the API key in R Studio, I encounter the following error. Could this problem be caused by my VPN? I can successfully log into ChatGPT on Google Chrome using my VPN.

gptstudio:::addin_chatgpt()
#> Error:
#> ! Recv failure: Connection reset by peer
#> Backtrace:
#>      ▆
#>   1. ├─gptstudio:::addin_chatgpt()
#>   2. │ └─gptstudio::check_api()
#>   3. │   └─gptstudio::check_api_connection(api_key)
#>   4. │     └─gptstudio:::simple_api_check(api_key)
#>   5. │       └─... %>% httr2::resp_status()
#>   6. ├─httr2::resp_status(.)
#>   7. │ └─httr2:::check_response(resp)
#>   8. │   └─httr2:::is_response(req)
#>   9. └─httr2::req_perform(.)
#>  10.   └─base::tryCatch(...)
#>  11.     └─base (local) tryCatchList(expr, classes, parentenv, handlers)
#>  12.       └─base (local) tryCatchOne(expr, names, parentenv, handlers[[1L]])
#>  13.         └─value[[3L]](cond)
Created on 2023-06-13 with [reprex v2.0.2](https://reprex.tidyverse.org/)

**Comment by lizongzhang** [comment]
I changed a VPN and solved the above problem. Thanks for developing gptstudios! It's great to use ChatGPT in R studio. The process of using is very smooth and efficient.

**Comment by JamesHWade** [comment]
Thank you for following up. Glad you are enjoying the package!
