### ISSUE TITLE
ERROR in install.packages("gptstudio") on Windows

### ISSUE THREAD

**Issue by LuuuXG** [MichelNivard/gptstudio#114]
When I was installing this package, I encountered the following error.

Error in parse(outFile) : 
  C:/Users/WYJ/AppData/Local/Temp/RtmpW6Ksiw/R.INSTALL263c70e7aa7/gptstudio/R/StreamHandler.R:76:20: unexpected input
75:         stringr::str_split_1("\n\ndata: ") %>%
76:         purrr::map(\
                               ^
ERROR: unable to collate and parse R files for package 'gptstudio'
* removing 'D:/Program Files/R/R-4.0.2/library/gptstudio'
Warning in install.packages :
  installation of package ‘gptstudio’ had non-zero exit status

![image](https://github.com/MichelNivard/gptstudio/assets/104219102/30e38641-9000-4ff8-9db3-4f6cde2a84c3)

**Comment by calderonsamuel** [comment]
Thank you for the report! It seems we are using a syntax not allowed for versions previous to R 4.1.0. 

For now, you could try installing the package in a more recent version of R, but that will surely mess with your current projects. I think if a few days we can have a patch in this repo for your problem.

**Comment by calderonsamuel** [comment]
Plase don't close it until we fix it! 🤣 

It will be closed once we get to a solution or we give up trying (highly unlikely)
