### ISSUE TITLE
Fail to make the connection when I use gptstudio

### ISSUE THREAD

**Issue by Torstudio** [MichelNivard/gptstudio#116]
when I use the addins ChatGpt, It runs as that below, an error of connection timeout occurs. I have never succeed to intall or use it, but I succeed to use the  url chat.openai.com. I find that many people have the same promblem. Anyone can help me ?Your help will be greatly appreciated .

> gptstudio:::addin_chatgpt()
! OPENAI_API_KEY is not set.
Do you want to set the OPENAI_API_KEY for this session?

1: Not now
2: Yes
3: Negative

Selection: 2
Copy and paste your API key here: <then I pasted my chatgpt api key here>
Error:
! Timeout was reached: [api.openai.com] Connection timeout after 10000 ms
Run `rlang::last_trace()` to see where the error occurred.

**Comment by calderonsamuel** [comment]
Thank you for your report!

This could mean that the chat app is not using the same environment than the session it is called from. The easiest way to fix this is by ussing an .Renviron file. 

```r
# install.packages("usethis")
usethis::edit_r_environ() # for all your R sessions
usethis::edit_r_environ("project") # for a single specific directory/project
```

Add an entry like this (it should always end in an empty new line):

```
OPENAI_API_KEY="paste-here-your-api-key"

```

After resetting your R session, you should be able to use the addin without further configuration. Let us know if this works for you.

For the developers, it means that `check_api()` is not setting the api key as expected. It also means  that our tests are not catching these things! I think this could be tested with an object inside the server of `mod_app()` where we could check for the existence of certain `options()` or environment variables.

---

If the addin doesn't ask you for an api key again, but the same problem persists (Connection timeout), you network could be blocking the requests. In that case, we would need more details about your connection

**Comment by JamesHWade** [comment]
It will be difficult for us to set the environment variable across sessions. We could try using ask pass to set the API key for that session, but a user-modified .Renviron file is the best route I think.

We could consider using `tools::R_user_dir()`, but that makes it harder for the user to know what API key they are using. [Here's more details on that approach for package data in general.](https://r-pkgs.org/data.html#sec-data-persistent).

**Comment by Torstudio** [comment]
Thank you @calderonsamuel @MichelNivard 
It seem to not wok.
when I run the code below , It will pop up two files of .Renviron from different locations.One from my working direction, that's also the gptstudio library location as I have set, if not , an error will occur like this "Error: Path 'D:/Rwd/' does not appear to be inside a project or package.Read more in the help for `proj_get()`." in the situation where I  set my work direction to the file named "Rwd". And one from C:/Users/Jun/Documents/.Renviron, that's the Windows user's default document location. 
I paste my chatgpt api code to the the two files and click save buttom to save them . and click addins→ChatGpt. and the pictures show what is going on. I have tried many times but still can't solve the problems. I am not sure if I am doing in the right way.


`# install.packages("usethis")`
`usethis::edit_r_environ() # for all your R sessions`
`usethis::edit_r_environ("project") # for a single specific directory/project`

`OPENAI_API_KEY="replace with my chatgpt api key and save the file"
`
![2023-06-20_20-36-56](https://github.com/MichelNivard/gptstudio/assets/137071717/9cc3d312-aaf4-4dc9-99e1-28b75afef7d4)

![2023-06-20_20-37-44](https://github.com/MichelNivard/gptstudio/assets/137071717/69def29d-e951-4345-923c-70b757691170)

![2023-06-20_20-39-44](https://github.com/MichelNivard/gptstudio/assets/137071717/3aa6ed5c-0a4c-4759-9daa-416dde479580)

**Comment by calderonsamuel** [comment]
Two things:

1. You have to choose if you want a .Renviron for all your sessions or only a project, you don't need to set both unless you really want to. In general, is best to set it for all sessions. Remember to reset your R session after editing your .Renviron file. It seems that you didn't do that. Just close RStudio an open it again to achieve that.
2. As I said before, if that doesn't fix it, you might have a network issue. Do you happen to be behind a proxy or VPN for your typical network usage? We don't currently support that but would like some help to test the package when we try to implement support for that

**Comment by Torstudio** [comment]
> Two things:
> 
> 1. You have to choose if you want a .Renviron for all your sessions or only a project, you don't need to set both unless you really want to. In general, is best to set it for all sessions. Remember to reset your R session after editing your .Renviron file. It seems that you didn't do that. Just close RStudio an open it again to achieve that.
> 2. As I said before, if that doesn't fix it, you might have a network issue. Do you happen to be behind a proxy or VPN for your typical network usage? We don't currently support that but would like some help to test the package when we try to implement support for that

1. I  have reset my R session by Ctrl+Shift+F10 ，but it is of no use, I have tried many times.
2. I do use a VPN. it is ok to visit the website chat.openai.com，so I don’t think there’s any problem..
3. I had imaged some other problems that may happened to me . I had tried in two different computers. I also registered a new chatgpt account to create a new api key, because the  previous one's "Free trial usage" had expired， I don't know if the "Free trial usage" is related to the api key. however, none of the solutions worked .

**Comment by JamesHWade** [comment]
What is the output of `gptstudio::check_api()`?

For some users, free accounts are causing causing 429 errors. Have you added payment details? See #100 for more details.

**Comment by Torstudio** [comment]
Here is the output:
`> gptstudio::check_api()
Error:
! Timeout was reached: [api.openai.com] Connection timeout after 10007 ms
Run `rlang::last_trace()` to see where the error occurred.`

**Comment by calderonsamuel** [comment]
This is most probably related to the VPN. As I said before, we currently don't support them but will try to in the near future. This is similar to #90

**Comment by Torstudio** [comment]
Thank you all @calderonsamuel @MichelNivard .
Hope for an update
