### ISSUE TITLE
Feature Request: Status Function for "sitrep"

### ISSUE THREAD

**Issue by JamesHWade** [MichelNivard/gptstudio#118]
To help with issues like #116 & #100, I suggest we create a `gptstudio_sitrep()` function that checks all APIs and reports to the use if it is set appropriately. If we want to be even fancier, we could use `{callr}` or to create a new session/job to see if the API key is only set for that session.

**Comment by calderonsamuel** [comment]
This is something I had in mind but didn't know how to express. I can work on this from next week when I will have a little more free time

**Comment by JamesHWade** [comment]
This could coincide with a simple settings app (or screen in current app) to change settings.

**Comment by JamesHWade** [comment]
Added gptstudio_sitrep() in #165
