### ISSUE TITLE
openai for R version 3.6.3

### ISSUE THREAD

**Issue by fcorowe** [MichelNivard/gptstudio#12]
Hi Michel,

Great package - I was planning to start using gptstudio but openai does not seem to be available for R version 3.6.3. Here is the output when I try installing the package:

```
ERROR: dependency ‘openai’ is not available for package ‘gptstudio’
* removing ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/gptstudio’
Warning messages:
1: package ‘openai’ is not available (for R version 3.6.3) 
2: In i.p(...) :
  installation of package ‘/var/folders/n7/k_dfmxgn3k79tvpfzffhhpqw0000gn/T//Rtmp47QzCe/filef90b37cad5dc/gptstudio_0.1.0.tar.gz’ had non-zero exit status
```

Any plans to release version compatible with R 3.6.3?

**Comment by MichelNivard** [comment]
This is a limitation of an package we depend on, openai, you can try and raise the issue with the developer of that package here (https://github.com/irudnyts/openai/issues ) , or if you are able update to R 4.2 or newer. There are ways to maintain 2 R installs if you need 3.6.3 for specific reasons.

**Comment by JamesHWade** [comment]
I created a PR to openai that should remove the dependency on R 4.2. Until then, you can install openai from my forked repo:

https://github.com/JamesHWade/openai

```
require(remotes)
remotes::install_github("JamesHWade/openai")
```
