### ISSUE TITLE
FR: Add feature to add custom instructions to chatgpt

### ISSUE THREAD

**Issue by tomasrei** [MichelNivard/gptstudio#121]
Great package! I was thinking that it would be great if you could add some custom/default prompts, so that interactions become more efficient. For example, I add "only code, no comments" at the end of many prompts.

Cheers,
Tom

**Comment by JamesHWade** [comment]
Thank you for the suggestion!

**Comment by calderonsamuel** [comment]
I think this is a duplicate of #86
