### ISSUE TITLE
Problem in the installation of the addin

### ISSUE THREAD

**Issue by lebjulien** [MichelNivard/gptstudio#13]
At the end of the installation, the console is returning me :
`ERROR: dependency  'openai' is not available for package 'aptstudio'` and `In i.p(…) :  installation of package '/tmp/RtmpMbf9UM/file4d275cf47c55/gptstudio_0.1.0.tar.qz' had non-zero exit status `

My R version is 4.0.5

Thank you for your help

**Comment by MichelNivard** [comment]
The dependency openai, which is essential for gptstudio, requires R version 4.2 or newer. You could ask whether that’s something that’s easily fixed by the openai developers here: https://github.com/irudnyts/openai/issues or update to a newer version of R if you are able too.

**Comment by JamesHWade** [comment]
I created a PR to openai that should remove the dependency on R 4.2. Until then, you can install openai from my forked repo:

https://github.com/JamesHWade/openai

```
require(remotes)
remotes::install_github("JamesHWade/openai")
```
