### ISSUE TITLE
Example for hugging face request

### ISSUE THREAD

**Issue by brunocarlin** [MichelNivard/gptstudio#140]
Can you guys provide the docs for a hugging face GPT in source request?

Also, the documentation to host your own hugging face model would be amazing!

Thanks for the great package

**Comment by JamesHWade** [comment]
My implementation in #165 would require a user to run the chat app and save settings to change out the model. 

Any objections to that approach?

**Comment by calderonsamuel** [comment]
I think it's ok to do that for  the model selection. Do we need documentation on setting up HF or which ENV variables to use? Will it be worth it to create a vignette about all the supported services to not clutter the README?

**Comment by JamesHWade** [comment]
Please see vignettes for examples for each service added in #165
