### ISSUE TITLE
ChatGPT responses cut short in Windows in gptstudio version 0.3.0

### ISSUE THREAD

**Issue by stmacdonell** [MichelNivard/gptstudio#142]
In windows using gptstudio 0.3.0. I can't see full responses from ChatGPT using the Shiny app. They are cut off and I get warnings and errors under Background Jobs.

As a recent example, after setting my OpenAI API key. I selected ChatGPT from the Addins menu, and then in the prompt area I entered:

"Tell me about ggplot"

I received:

"ggplot is a powerful data visualization package in R programming. It is known for generating high-quality and customizable statistical graphics. With ggplot, you can create a wide range of visualizations including scatter plots, bar charts, line plots, histograms, box plots" (I can tell this is cut off by the lack of an "and" or period at the end)

At this point a warning was added to Background Job which then reads:
"Loading required package: shiny

Listening on http://127.0.0.1:7877
Not chat history found.
Warning: Error in readRDS: error reading from connection
  122: readRDS
  120: <Anonymous>
  118: valueFunc
  117: <reactive>
  101: reactive_stream
  100: renderUI
   99: func
   86: renderFunc
   85: output$app-chat-streaming
    4: shiny::runApp
    3: eval
    2: eval
    1: .rs.sourceWithProgress"

Next I added

"Show me a ggplot example please."

the prior response was removed from the window and the following added:

"Certainly! Here's a simple example of a scatter plot using ggplot in R:

language-{r}

library"

...with nothing more. The following appeared under background jobs:
"Background session status: 200, done callr-rs-result-2f7058837bf0, NULL, ,
 , and list(message = "in callr session.
subprocess.", srcref = NULL, status = 0, stdout = "", stderr = "Deleting chat
history from this session.\r\n", parent_trace = list(parent = c(12, 13, 15, 15,
17, 18, 19, 19, 20, 22, 22, 22, 24, 25, 26, 0, 28), visible = c(TRUE, TRUE,
TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE,
TRUE, TRUE), namespace = c(NA, NA, "gptstudio", "base", "gptstudio",
"gptstudio", "gptstudio", "gptstudio", NA, NA, "base", NA, "gptstudio", "base",
"base", "base", NA), scope = c("", "", ":::", "::", "::", "::", ":::", "::",
"", "", "::", "local", ":::", "::", "::", "::", "global"), srcref = list(NULL,
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
NULL, NULL, NULL), procsrcref = list(NULL, NULL, NULL, NULL, NULL, NULL, NULL,
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL), pid = c(23256,
23256, 23256, 23256, 23256, 23256, 23256, 23256, 23256, 23256, 23256, 23256,
23256, 23256, 23256, 23256, 23256), call =
list("gptstudio::gptstudio_job(skeleton, skill, style, task, custom_prompt)",
c("gptstudio_skeleton_build(skeleton, skill, style, task, custom_prompt) %>% ",
" gptstudio_request_perform() %>% gptstudio_response_process() %>% "),
"save_skeleton(.)", "saveRDS(skeleton, skeleton_file())",
"gptstudio_response_process(.)", "gptstudio_request_perform(.)",
"gptstudio_request_perform.gptstudio_request_openai(.)",
"stream_chat_completion(prompt = messages, model = model)",
c("httr2::request(base_url) %>%
httr2::req_url_path_append(\"chat/completions\") %>% ", "
httr2::req_body_json(body) %>% httr2::req_auth_bearer_token(openai_api_key) %>%
" ), c("httr2::req_stream(., callback = function(x) {", "
openai_stream_parse(x)"), "isTRUE(callback(buf))", "callback(buf)",
"openai_stream_parse(x)", "saveRDS(gptstudio_env$stream$parsed, file =
streaming_file())", "gzfile(file, mode)", c(".handleSimpleError(function (e) ",
"{"), "h(simpleError(msg, call))")), call = NULL, procsrcref = NULL, parent =
list(message = "cannot open the connection", call = "gzfile(file, mode)",
srcref = NULL, procsrcref = NULL))"

On Ubuntu everything runs fine with 0.3.0 (dual boot, same physical machine on the same network as one of the Windows installs I'm having trouble with), On three separate Windows (10 and 11) machines on different network setups (work and home and a VPN between) I never seem to see full responses from my prompts. I'm running R 4.3.1 and RStudio 2023.06.1 Build 524. I've used both install.packages("gptstudio") grabbing the binary, and  remotes::install_version("gptstudio", version = "0.3.0") which installed from source as well as pak::pak("MichelNivard/gptstudio"). Rolling back with  remotes::install_version("gptstudio", version = "0.2.0") solves the issue.

**Comment by JamesHWade** [comment]
Thank you for reporting. This will take some investigating to better understand what's going wrong.

**Comment by julieaaj** [comment]
Hi! Just wanted to let you know I am facing the exact same problem. Using Windows and same R versions as above example. Fresh install of gptstudio today!

**Comment by HilianoMop** [comment]
I had same problem while using Windows with those new versions.
but running the old GPTstudio version as per: remotes::install_version("gptstudio", version = "0.2.0") solved the issue here.
Many thanks!

I hope they will fix that!

**Comment by JamesHWade** [comment]
Yes, definitely plan to fix. I have an idea to try.
