### ISSUE TITLE
Ive followed the steps, I see the bot but when I ask it anything it doesnt work, it doesnt give any response back... Any idea how to fix this? 

### ISSUE THREAD

**Issue by Chimmyj390j2** [MichelNivard/gptstudio#147]
<img width="470" alt="Screenshot 2023-10-02 at 5 58 25 PM" src="https://github.com/MichelNivard/gptstudio/assets/120446516/88ca1f84-24e5-42e9-a495-ee425014ebbe">
<img width="150" alt="Screenshot 2023-10-02 at 5 59 44 PM" src="https://github.com/MichelNivard/gptstudio/assets/120446516/70dc815d-9968-4cb3-aa27-f95770f181f9">
<img width="1004" alt="Screenshot 2023-10-02 at 6 00 19 PM" src="https://github.com/MichelNivard/gptstudio/assets/120446516/c282364b-9057-42e9-9617-5685bf0f25f3">

**Comment by calderonsamuel** [comment]
Have you tried after restarting the R session? You can do that in the session menu of RStudio or just closing and opening again RStudio.

If that doesn't work please try with v0.2.0, it has fewer features but might be enough for your use case.

```r
# install.packages("remotes")
remotes::install_version("gptstudio", version = "0.2.0")
```

**Comment by Chimmyj390j2** [comment]
well it did something, now I can see the bot in the chat but still no response, maybe its a mac thing.. 
<img width="383" alt="Screenshot 2023-10-03 at 3 39 54 PM" src="https://github.com/MichelNivard/gptstudio/assets/120446516/7befe00e-06fc-4a00-be7e-605d79287ec7">

**Comment by calderonsamuel** [comment]
This looks a lot like #100 . In summary, OpenAI should be able to charge you more than $0.00 for API requests. Let us know if that was the issue

**Comment by calderonsamuel** [comment]
With no further information, I suggest we close this @JamesHWade
