### ISSUE TITLE
OPENAI_API_KEY is not valid.

### ISSUE THREAD

**Issue by wangguiqian** [MichelNivard/gptstudio#156]
Loading required package: shiny

Listening on http://127.0.0.1:5017
! OPENAI_API_KEY is not valid.
ℹ Generate a key at <https://platform.openai.com/account/api-keys>
ℹ Set the key in your .Renviron file usethis::edit_r_environ()
Warning: Error in httr2::req_perform: Failed to perform HTTP request.
Caused by error in `curl::curl_fetch_memory()`:
! Timeout was reached: [api.openai.com] Connection timed out after 10000 milliseconds
  92: <Anonymous>
  91: signalCondition
  90: signal_abort
  89: cnd_signal
  88: handle_resp
  87: httr2::req_perform
  86: is_response
  85: check_response
  84: httr2::resp_body_json
  83: pluck_raw
  82: purrr::pluck
  81: vctrs_vec_compat
  80: map_
  79: purrr::map_chr
  78: %>%
  77: get_available_models
  76: observe
  75: <observer>
   4: shiny::runApp
   3: eval
   2: eval
   1: .rs.sourceWithProgress
Warning: Error in : API key is not valid
  85: <Anonymous>
  78: gptstudio_skeleton_build
  76: observe
  75: <observer>
   4: shiny::runApp
   3: eval
   2: eval
   1: .rs.sourceWithProgress
Warning: Error in : API key is not valid
  85: <Anonymous>
  78: gptstudio_skeleton_build
  76: observe
  75: <observer>
   4: shiny::runApp
   3: eval
   2: eval
   1: .rs.sourceWithProgress
! OPENAI_API_KEY is not valid.
ℹ Generate a key at <https://platform.openai.com/account/api-keys>
ℹ Set the key in your .Renviron file usethis::edit_r_environ()
Warning: Error in httr2::req_perform: Failed to perform HTTP request.
Caused by error in `curl::curl_fetch_memory()`:
! Timeout was reached: [api.openai.com] Connection timed out after 10000 milliseconds

**Comment by calderonsamuel** [comment]
Please try with the development version:

```r
# install.packages("pak")
pak::pak("MichelNivard/gptstudio")
```

**Comment by wangguiqian** [comment]
> gptstudio:::addin_chatgpt()
✔ gptstudio initialized as background job in RStudio
ℹ Showing app in 'Viewer' pane
ℹ Run rstudioapi::viewer("http://127.0.0.1:7362") to see it
> usethis::edit_r_environ()
• Modify '/Users/wang/.Renviron'
• Restart R for changes to take effect
> rstudioapi::viewer("http://127.0.0.1:7362")
> curl::curl_fetch_memory()
Error in curl::curl_fetch_memory() : 
  argument "url" is missing, with no default

Loading required package: shiny

Listening on http://127.0.0.1:7362
! OPENAI_API_KEY is not valid.
ℹ Generate a key at <https://platform.openai.com/account/api-keys>
ℹ Set the key in your .Renviron file usethis::edit_r_environ()
Warning: Error in httr2::req_perform: Failed to perform HTTP request.
Caused by error in `curl::curl_fetch_memory()`:
! Timeout was reached: [api.openai.com] Connection timed out after 10003 milliseconds
  92: <Anonymous>
  91: signalCondition
  90: signal_abort
  89: cnd_signal
  88: handle_resp
  87: httr2::req_perform
  86: is_response
  85: check_response
  84: httr2::resp_body_json
  83: pluck_raw
  82: purrr::pluck
  81: vctrs_vec_compat
  80: map_
  79: purrr::map_chr
  78: %>%
  77: get_available_models
  76: observe
  75: <observer>
   4: shiny::runApp
   3: eval
   2: eval
   1: .rs.sourceWithProgress
! OPENAI_API_KEY is not valid.
ℹ Generate a key at <https://platform.openai.com/account/api-keys>
ℹ Set the key in your .Renviron file usethis::edit_r_environ()
Warning: Error in httr2::req_perform: Failed to perform HTTP request.
Caused by error in `curl::curl_fetch_memory()`:
! Timeout was reached: [api.openai.com] Connection timed out after 10002 milliseconds
  92: <Anonymous>
  91: signalCondition
  90: signal_abort
  89: cnd_signal
  88: handle_resp
  87: httr2::req_perform
  86: is_response
  85: check_response
  84: httr2::resp_body_json
  83: pluck_raw
  82: purrr::pluck
  81: vctrs_vec_compat
  80: map_
  79: purrr::map_chr
  78: %>%
  77: get_available_models
  76: observe
  75: <observer>
   4: shiny::runApp
   3: eval
   2: eval
   1: .rs.sourceWithProgress

**Comment by JamesHWade** [comment]
Please re-open if the dev version did not fix your issue.
