### ISSUE TITLE
Error in curl::curl_fetch_memory(url, handle = handle)

### ISSUE THREAD

**Issue by wangguiqian** [MichelNivard/gptstudio#157]
library(httr)
> api_key <- Sys.getenv("OPENAI_API_KEY")
> response <-GET("https://api.openai.com/v1/models"  ,add_headers(Authorization = paste0("Bearer ", api_key)))
     Error in curl::curl_fetch_memory(url, handle = handle) : 
     Timeout was reached: [api.openai.com] Connection timed out after 10000 milliseconds

I don't no solve the quetion.

**Comment by calderonsamuel** [comment]
This is because of a change in the response from the openai endpoint. Please try with the development version:

```r
# install.packages("pak")
pak::pak("MichelNivard/gptstudio")
```

**Comment by wangguiqian** [comment]
I try to run pak::pak("MichelNivard/gptstudio"),then get the questions .

Loading required package: shiny

Listening on http://127.0.0.1:7362
! OPENAI_API_KEY is not valid.
ℹ Generate a key at <https://platform.openai.com/account/api-keys>
ℹ Set the key in your .Renviron file usethis::edit_r_environ()
Warning: Error in httr2::req_perform: Failed to perform HTTP request.
Caused by error in `curl::curl_fetch_memory()`:
! Timeout was reached: [api.openai.com] Connection timed out after 10003 milliseconds
  92: <Anonymous>
  91: signalCondition
  90: signal_abort
  89: cnd_signal
  88: handle_resp
  87: httr2::req_perform
  86: is_response
  85: check_response
  84: httr2::resp_body_json
  83: pluck_raw
  82: purrr::pluck
  81: vctrs_vec_compat
  80: map_
  79: purrr::map_chr
  78: %>%
  77: get_available_models
  76: observe
  75: <observer>
   4: shiny::runApp
   3: eval
   2: eval
   1: .rs.sourceWithProgress
! OPENAI_API_KEY is not valid.
ℹ Generate a key at <https://platform.openai.com/account/api-keys>
ℹ Set the key in your .Renviron file usethis::edit_r_environ()
Warning: Error in httr2::req_perform: Failed to perform HTTP request.
Caused by error in `curl::curl_fetch_memory()`:
! Timeout was reached: [api.openai.com] Connection timed out after 10002 milliseconds
  92: <Anonymous>
  91: signalCondition
  90: signal_abort
  89: cnd_signal
  88: handle_resp
  87: httr2::req_perform
  86: is_response
  85: check_response
  84: httr2::resp_body_json
  83: pluck_raw
  82: purrr::pluck
  81: vctrs_vec_compat
  80: map_
  79: purrr::map_chr
  78: %>%
  77: get_available_models
  76: observe
  75: <observer>
   4: shiny::runApp
   3: eval
   2: eval
   1: .rs.sourceWithProgress

**Comment by wangguiqian** [comment]
gptstudio:::addin_chatgpt()
✔ gptstudio initialized as background job in RStudio
ℹ Showing app in 'Viewer' pane
ℹ Run rstudioapi::viewer("http://127.0.0.1:7362") to see it
> usethis::edit_r_environ()
• Modify '/Users/wang/.Renviron'
• Restart R for changes to take effect
> rstudioapi::viewer("http://127.0.0.1:7362")
> curl::curl_fetch_memory()
Error in curl::curl_fetch_memory() : 
  argument "url" is missing, with no default

**Comment by calderonsamuel** [comment]
This line 

```r
#> ! Timeout was reached: [api.openai.com] Connection timed out after 10002 milliseconds
```

suggests that you might me having network connection issues. maybe you are connecting to the internet behind using a VPN or proxy? We support changing the default OpenAI url, you can use:

```r
options(gptstudio.openai_url = "your_url_here")
```

Look at what other people have reported before: #90 , #119 , #124
