### ISSUE TITLE
Spell checking

### ISSUE THREAD

**Issue by MonsieurDewey** [MichelNivard/gptstudio#158]
I have installed the github version of gptstudio using pak.  The chat function seems to work fine, but the spell checking doesn't.  I create a quarto document, put a sentence in it with bad spelling, select the sentence, and then go to the addin menu item for spell checking.  It acts as though it doesn't receive any text to spell check.  It just returns with, "I can help you with spell checking."

Thanks!

Scott

**Comment by calderonsamuel** [comment]
Thank you for your report, I'll be looking into this
