### ISSUE TITLE
Error Executing Addin

### ISSUE THREAD

**Issue by Chester1024** [MichelNivard/gptstudio#160]
![image](https://github.com/MichelNivard/gptstudio/assets/152573635/401f4d42-8d68-4968-92a0-76bf06a5a80e)
I'm using R Studio in mac to run the plugin, but it doesn't work. Also in the dialog box, I can't get a response.
![image](https://github.com/MichelNivard/gptstudio/assets/152573635/aecc8ebc-a2e6-4b63-a511-481089176026)

**Comment by calderonsamuel** [comment]
Please try again with the development version:

```r
# install.packages("pak")
pak::pak("MichelNivard/gptstudio")
```

**Comment by Chester1024** [comment]
> Please try again with the development version:
> 
> ```r
> # install.packages("pak")
> pak::pak("MichelNivard/gptstudio")
> ```

Thank you. I tried, but still have the same question.

**Comment by calderonsamuel** [comment]
Thank you. I need more info to debug this. When does the error occur? is it when clicking the addin? is it when you send a prompt? do you have a valid API key from OpenAI linked to an account that can be charged?

**Comment by JamesHWade** [comment]
Closing for now. Please re-open if you have additional info to help with debugging @Chester1024.
