### ISSUE TITLE
Release gptstudio 0.4

### ISSUE THREAD

**Issue by JamesHWade** [MichelNivard/gptstudio#163]
Prepare for release:

* [ ] Complete #164
* [x] `git pull`
* [x] Check [current CRAN check results](https://cran.rstudio.org/web/checks/check_results_gptstudio.html)
* [x] [Polish NEWS](https://style.tidyverse.org/news.html#news-release)
* [x] `urlchecker::url_check()`
* [x] `devtools::build_readme()`
* [x] `devtools::check(remote = TRUE, manual = TRUE)`
* [x] `devtools::check_win_devel()`
* [x] `revdepcheck::revdep_check(num_workers = 4)`
* [x] Update `cran-comments.md`
* [x] `git push`
* [ ] Draft blog post

Submit to CRAN:

* [x] `usethis::use_version('minor')`
* [x] `devtools::submit_cran()`
* [x] Approve email

Wait for CRAN...

* [x] Accepted :tada:
* [ ] Add preemptive link to blog post in pkgdown news menu
* [x] `usethis::use_github_release()`
* [x] `usethis::use_dev_version(push = TRUE)`
* [x] Finish blog post
* [ ] Tweet

**Comment by calderonsamuel** [comment]
Hey James, I saw that it's on its way  to CRAN. Thank you for that. Should we work some kind of blog post for it? We don't have an official blog but we might use the Discussions or Wiki tabs of the repo

**Comment by JamesHWade** [comment]
A blog post would be great! Is that something you'd be interested in
drafting?

**Comment by calderonsamuel** [comment]
I'll have a draft tomorrow if that's ok

**Comment by calderonsamuel** [comment]
It's here https://github.com/MichelNivard/gptstudio/discussions/210

Please feel free to edit/remove as you like. I'm not totally convinced of the title 🤔

**Comment by JamesHWade** [comment]
You are the best!

**Comment by calderonsamuel** [comment]
Hey @JamesHWade , let me know if we can consider this one as completed
