### ISSUE TITLE
Upkeep for gptstudio (2024)

### ISSUE THREAD

**Issue by JamesHWade** [MichelNivard/gptstudio#164]
* [x] `usethis::use_tidy_description()`
* [x] Align the names of `R/` files and `test/` files for workflow happiness. The docs for `usethis::use_r()` include a helpful script. `usethis::rename_files()` may be be useful.
* [x] Add alt-text to pictures, plots, etc; see <https://posit.co/blog/knitr-fig-alt/> for examples

Set up or update GitHub Actions. \
      Updating workflows to the latest version will often fix troublesome actions:
* [x] `usethis::use_github_action('check-standard')`
* [x] `usethis::use_github_action('pkgdown')`
* [x] `usethis::use_github_action('test-coverage')`

<sup>Created on 2024-01-08 with `usethis::use_upkeep_issue()`, using [usethis v2.2.2](https://usethis.r-lib.org)</sup>

- [x] Update home page examples to reflect new UIs
- [x] Create example for using local model
- [x] Update Google AI Studio to Gemini

**Comment by JamesHWade** [comment]
@calderonsamuel, I'm coming back from parental leave soon, and I want to give a lot more time to this package. Thought I'd start that off with an "upkeep" issue created with `usethis::use_upkeep_issue()`.

Anything else you'd like to add? After this, it seems like a good time to issue a new release given all your fantastic recent contributions.

**Comment by JamesHWade** [comment]
#165

**Comment by calderonsamuel** [comment]
Hi James, glad to have you back! I think we need to solve the bugs listed in issues and improve some documentation.

- #161 
- #140 
- Match translations to the new UI elements
- #118 ??? 
- #128 ???

I would also like to have some features implemented before v0.4.0:

- #105 We already have HF. Ollama is awesome and can be quickly implemented for local models.
- A more dynamic model selection or settings generation. For azure + openai, you don't really choose the model when you perform a request, instead you do it when you "deploy" it. For that reason we were using the deployment name as "model", but they are different things.
- Reduce hard-coded CSS styling. I'm finding that the bslib team is continually making changes to some UI elements (e.g. sidebars) and they might conflict with our current styling.

## v0.5.0

Thinking a bit about the near future, I think we should aim to achieve two things:

1. Migrate the *build skeleton -> perform request -> translate response* process to S7 to have explicit "type safety" and extendability. The S7 classes and generics necessary should live in another package, where they should be documented, so gptstudio can focus on improving the chatgpt addin and the others. I'm working on a draft for such package in [calderonsamuel/skellm](https://github.com/calderonsamuel/skellm). This will also mean that, eventually, other packages can wrap new APIs and the gptstudio addins will find their methods without depending on them (e.g. I'm already drafting how we can do that for ollama in [calderonsamuel/ollama](https://github.com/calderonsamuel/ollama).
2. Improve testing tooling. Here we should focus on test coverage and testing on CI (at least the *free* services).

## v1.0.0

At some point we should reach an actual stable  version. I would like to have these features, they are both pretty challeging:

- #66 . Can be whisper or any other service.
- #133 Check the conversation for some status.

**Comment by JamesHWade** [comment]
Great ideas. I updated them to tasks for us to work on. Thanks again for all of you fantastic work on this package! I'm excited by your `{skellm}` package.

**Comment by JamesHWade** [comment]
@calderonsamuel, you might be interested in this PR from httr2:

https://github.com/r-lib/httr2/pull/437

It might make our lives a lot easier in parsing JSON from streams.

**Comment by JamesHWade** [comment]
@calderonsamuel , I'd like to submit 0.4 to CRAN with in the next few weeks. Do you think you'll have time to work on some of the items you mention above over the newt couple of weeks?

If so, let me know what you plan to work on, and I'll try to cover any of the remaining tasks.

**Comment by calderonsamuel** [comment]
> @calderonsamuel , I'd like to submit 0.4 to CRAN with in the next few weeks. Do you think you'll have time to work on some of the items you mention above over the newt couple of weeks?
> 
> If so, let me know what you plan to work on, and I'll try to cover any of the remaining tasks.

Hi James. I can focus on reducing the hard coded css and the dynamic model selection. Also I can help with fixing bug reports

**Comment by calderonsamuel** [comment]
Hey James, I think we should push v0.4.0 to CRAN and move the pending issues to v0.5.0. The current CRAN version crashes in different scenarios that have long been fixed in the develpment branch. Also, lots of newbies don't know how to install from github. Just give time to fix #202 and we should be good to go

**Comment by JamesHWade** [comment]
Let's do it. Is next week a good target?

**Comment by JamesHWade** [comment]
I'll plan to send this off to CRAN tomorrow unless I hear any objections. Excited to get this next version out there!!!

**Comment by calderonsamuel** [comment]
I'll just like your opinion on keeping the following elemets:

1. Sidebar > Settings > "Save settings for this session" 
2. Sidebar > "Delete all chats"

They were useful for the development, but I'm not sure if final users will them useful too.

**Comment by JamesHWade** [comment]
I use them all the time, so I say keep them.

**Comment by calderonsamuel** [comment]
I have a lot of small updates in my mind, but I don't want us to lose the momentum. Lets go to CRAN

**Comment by JamesHWade** [comment]
I have it ready to submit Monday morning. I forgot they don't like submissions on the weekends.

**Comment by JamesHWade** [comment]
Closing since we have missing features called out as separate issues.
