### ISSUE TITLE
gptstudio "analysis" shiny pane?

### ISSUE THREAD

**Issue by MichelNivard** [MichelNivard/gptstudio#17]
@JamesHWade, I was thinking could we re-use your "datasummary" input from gpttools and prompt davinci-003 with both:

"the summary"

the users specific analysis question about their own data (example "Can you regress BMI on age, sex, exercise and use a mixed model with a random intercept for zipcode use lme4")

I think this would likely lead to a higher likelihood gpt gets the variable names etc right?

**Comment by JamesHWade** [comment]
First draft in #22

**Comment by MichelNivard** [comment]
If I try to switch between two dataframes it fails to do so (the dropdown jumps back to the previous selection), it does generate prompts correctly and other functionality seems okay so far! I wonder whether we should let people provide the model prompt explicitly in a textbox on the left-hand side from a UI perspective (its input, while entirely on the right hand side of the app is output.)

**Comment by JamesHWade** [comment]
Both should be easy enough to implement...

**Comment by JamesHWade** [comment]
Changes are in #23

**Comment by MichelNivard** [comment]
The shiny app broke; I think the value of input$prompt isn't a character string anymore, so openai trips up, and on my machine the new way of setting the output to pane fails, and I get the app as a pop-up which obscures the view of the rest of RStudio. I am trying to figure out a way to fix it as we speak. I think I have a solution for the prompt failing

**Comment by JamesHWade** [comment]
Crap... I'll fix when I'm back at my computer.

**Comment by MichelNivard** [comment]
So I figure out the issue but can't get a fix in because I don't know a workaround yet, but basically the input$prompt goes to openai_create_competion(), while the updated prompt are fed to output$prompt, which leaves input prompt NULL. So perhaps go back to the old process and instruct ppl to complete the prompt with their request manually? ?

**Comment by MichelNivard** [comment]
Yeah maybe revise back to a "textAreaInput()" to display the full prompt and use " updateTextAreaInput()" to update the input prompt. Then on click the submit button that's submitted. So much has moved around in the code that I can figure out how to do that without breaking things in the tie I have now.

**Comment by MichelNivard** [comment]
Fixed the pane issue as well. Closing, for now, can start a new issue if we want to discuss further functionality.
