### ISSUE TITLE
Links to Setup instructions in README are not working

### ISSUE THREAD

**Issue by apsalverda** [MichelNivard/gptstudio#180]
Links to Setup instructions in the table below are not working:
<img width="860" alt="image" src="https://github.com/MichelNivard/gptstudio/assets/9888903/0fac0db0-137d-423d-b398-c83a4cf8b5a5">

Clicking on a link in the Setup column results in this error:
<img width="526" alt="image" src="https://github.com/MichelNivard/gptstudio/assets/9888903/2f353403-f5a9-4bc4-a1a6-730497dce31e">

**Comment by calderonsamuel** [comment]
Hey @JamesHWade , can you work on this one? 🙏

**Comment by JamesHWade** [comment]
This is now fixed.
