### ISSUE TITLE
Chat doesn't respond

### ISSUE THREAD

**Issue by JuliusGr01** [MichelNivard/gptstudio#184]
Hey everyone!

I am running into some problems setting up the chat. I have set up everything according to your instructions (once in RStudio Desktop and once in Posit Cloud).
In both I run into the same problem:
When calling gptstudio:::addin_chatgpt() the Viewer starts the chat interface but the chat doesn't respond.

Here a more detailed description of what happens:

```r
install.packages("pak")
pak::pak("usethis")
pak::pak("gptstudio")

usethis::edit_r_environ()
Sys.getenv("OPENAI_API_KEY")
#Returns the right key

gptstudio:::addin_chatgpt()
```

 I get the following output in my terminal when running the command:
```r
✔ gptstudio initialized as background job in RStudio
ℹ Showing app in 'Viewer' pane
ℹ Run rstudioapi::viewer("http://127.0.0.1:7646") to see it
Connected to your session in progress, last started 2024-Mar-06 10:40:50 UTC (17 minutes ago)
```
The chatbot opens but doesn't react to prompts. If I try to change the settings I get the following error as soon as I klick on the setting button:

Warning: Error in purrr::map_chr: ℹ In index: 1.
Caused by error:
! Result must be length 1, not 0.
  80: <Anonymous>
  79: signalCondition
  78: signal_abort
  77: rlang::abort
  76: cli::cli_abort
  75: h
  74: .handleSimpleError
  73: call_with_cleanup
  70: map_
  69: purrr::map_chr
  68: %>%
  67: get_available_models
  66: <reactive>
  50: models
  48: observe
  47: <observer>
   4: shiny::runApp
   3: eval
   2: eval
   1: .rs.sourceWithProgress
Deleting chat history from this session.

I have verified that the key is correct (Sys.getenv("OPENAI_API_KEY") spits out the right key which I also newly generated)
I am using the code below which shouldn't be the problem:

```r
install.packages("pak")

pak::pak("usethis")
pak::pak("gptstudio")

usethis::edit_r_environ()
Sys.getenv("OPENAI_API_KEY")

gptstudio:::addin_chatgpt()
```

Any help would be appreciated. 

Best
Julius

**Comment by JamesHWade** [comment]
Hi Julius, thanks for the report. Is it working now? I see you closed the issue but wanted to double check.
