### ISSUE TITLE
Update bug report template in repo

### ISSUE THREAD

**Issue by calderonsamuel** [MichelNivard/gptstudio#186]
We should add instructions to paste the output of `session_info::session_info(pkgs = "gptstudio")` to any bug report in order to have better context. 

I'm in doubt about also requiring to install the development version before filling a bug report...

**Comment by JamesHWade** [comment]
Update to bug report instructions sounds good to me. For now, it's a good idea to ask users to install dev version, but I hope we can reach a point of stability in later releases where that won't be necessary.

**Comment by calderonsamuel** [comment]
Quick update, I received write access to this repo from @MichelNivard . I'll still use PRs and request your reviews @JamesHWade. I think the main difference will be that my PRs will now come from branches in this repo and that I'll be able to get notifications for issues and discussions

**Comment by JamesHWade** [comment]
I asked him to add you 😊. You should also be able to request code reviews, run checks, and merge reviewed PRs.
