### ISSUE TITLE
Error when using chatgpt window

### ISSUE THREAD

**Issue by smalltiger-moquan** [MichelNivard/gptstudio#191]
The first time I use the chatgpt window, it shows the following error and I can use the chatgpt in source function normally! ：

Background session status: 200, done callr-rs-result-12d076498d03d, NULL, ,
Deleting chat history from this session. , and list(message = "in callr
subprocess.", srcref = NULL, status = 0, stdout = "", stderr = "Deleting chat
history from this session.\n", parent_trace = list(parent = c(12, 13, 15, 15,
17, 18, 19, 19, 20, 21, 0, 23), visible = c(TRUE, TRUE, TRUE, TRUE, TRUE, TRUE,
TRUE, TRUE, TRUE, TRUE, TRUE, TRUE), namespace = c(NA, NA, "gptstudio", "base",
"gptstudio", "gptstudio", "gptstudio", "gptstudio", "base", "base", "base",
NA), scope = c("", "", ":::", "::", "::", "::", ":::", "::", "::", "::", "::",
"global" ), srcref = list(NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
NULL, NULL, NULL), procsrcref = list(NULL, NULL, NULL, NULL, NULL, NULL, NULL,
NULL, NULL, NULL, NULL, NULL), pid = c(77081, 77081, 77081, 77081, 77081,
77081, 77081, 77081, 77081, 77081, 77081, 77081), call =
list("gptstudio::gptstudio_job(skeleton, skill, style, task, custom_prompt)",
c("gptstudio_skeleton_build(skeleton, skill, style, task, custom_prompt) %>% ",
" gptstudio_request_perform() %>% gptstudio_response_process() %>% " ),
"save_skeleton(.)", "saveRDS(skeleton, skeleton_file())",
"gptstudio_response_process(.)", "gptstudio_request_perform(.)",
"gptstudio_request_perform.gptstudio_request_openai(.)",
"stream_chat_completion(prompt = messages, model = model)",
"readRDS(streaming_file())", "gzfile(file, \"rb\")",
c(".handleSimpleError(function (e) ", "{"), "h(simpleError(msg, call))")), call
= NULL, procsrcref = NULL, parent = list(message = "cannot open the
connection", call = "gzfile(file, \"rb\")", srcref = NULL, procsrcref = NULL))

When I open the chatgpt window again, it crashes with the following error, especially after clicking on the setup button：

✖ API key not found or is not formatted correctly.Attempted to validate key: <sk-*********************************************4zW>Generate a key at <https://platform.openai.com/account/api-keys>
Warning: Error in httr2::req_perform: HTTP 401 Unauthorized.
• OAuth error
• realm: OpenAI API
  83: <Anonymous>
  82: signalCondition
  81: signal_abort
  80: abort
  79: resp_abort
  78: handle_resp
  77: httr2::req_perform
  76: is_response
  75: check_response
  74: httr2::resp_body_json
  73: pluck_raw
  72: purrr::pluck
  71: vctrs_vec_compat
  70: map_
  69: purrr::map_chr
  68: %>%
  67: get_available_models
  66: <reactive>
  50: models
  48: observe
  47: <observer>
   4: shiny::runApp
   3: eval
   2: eval
   1: .rs.sourceWithProgress
Deleting chat history from this session.

But  I can use the chatgpt in source function normally!

**Comment by calderonsamuel** [comment]
Hi, can you paste the output of running `sessioninfo::session_info(pkgs = "gptstudio")` in the console?

Also, installing the development version might help:

```r
# install.packages("pak")
pak::pak("MichelNivard/gptstudio")
```

**Comment by smalltiger-moquan** [comment]
> gptstudio:::addin_chatgpt()
✔ gptstudio initialized as background job in RStudio
ℹ Showing app in 'Viewer' pane
ℹ Run rstudioapi::viewer("http://127.0.0.1:6868") to see it
> sessioninfo::session_info(pkgs = "gptstudio")
─ Session info ──────────────────────────────────────────────────────────────────────────────
 setting  value
 version  R version 4.3.2 (2023-10-31)
 os       macOS Sonoma 14.0
 system   aarch64, darwin20
 ui       RStudio
 language (EN)
 collate  en_US.UTF-8
 ctype    en_US.UTF-8
 tz       Asia/Shanghai
 date     2024-04-03
 rstudio  2023.12.1+402 Ocean Storm (desktop)
 pandoc   NA

─ Packages ──────────────────────────────────────────────────────────────────────────────────
 package     * version date (UTC) lib source
 askpass       1.2.0   2023-09-03 [1] CRAN (R 4.3.0)
 assertthat    0.2.1   2019-03-21 [1] CRAN (R 4.3.0)
 base64enc     0.1-3   2015-07-28 [1] CRAN (R 4.3.0)
 bslib         0.7.0   2024-03-29 [1] CRAN (R 4.3.1)
 cachem        1.0.8   2023-05-01 [1] CRAN (R 4.3.0)
 callr         3.7.6   2024-03-25 [1] CRAN (R 4.3.1)
 cli           3.6.2   2023-12-11 [1] CRAN (R 4.3.1)
 colorspace    2.1-0   2023-01-23 [1] CRAN (R 4.3.0)
 commonmark    1.9.1   2024-01-30 [1] CRAN (R 4.3.1)
 crayon        1.5.2   2022-09-29 [1] CRAN (R 4.3.0)
 curl          5.2.1   2024-03-01 [1] CRAN (R 4.3.1)
 digest        0.6.35  2024-03-11 [1] CRAN (R 4.3.1)
 evaluate      0.23    2023-11-01 [1] CRAN (R 4.3.1)
 fastmap       1.1.1   2023-02-24 [1] CRAN (R 4.3.0)
 fontawesome   0.5.2   2023-08-19 [1] CRAN (R 4.3.0)
 fs            1.6.3   2023-07-20 [1] CRAN (R 4.3.0)
 glue          1.7.0   2024-01-09 [1] CRAN (R 4.3.1)
 gptstudio     0.3.0   2023-07-11 [1] CRAN (R 4.3.0)
 highr         0.10    2022-12-22 [1] CRAN (R 4.3.0)
 htmltools     0.5.8   2024-03-25 [1] CRAN (R 4.3.1)
 htmlwidgets   1.6.4   2023-12-06 [1] CRAN (R 4.3.1)
 httpuv        1.6.15  2024-03-26 [1] CRAN (R 4.3.1)
 httr2         1.0.0   2023-11-14 [1] CRAN (R 4.3.1)
 jquerylib     0.1.4   2021-04-26 [1] CRAN (R 4.3.0)
 jsonlite      1.8.8   2023-12-04 [1] CRAN (R 4.3.1)
 knitr         1.45    2023-10-30 [1] CRAN (R 4.3.1)
 later         1.3.2   2023-12-06 [1] CRAN (R 4.3.1)
 lifecycle     1.0.4   2023-11-07 [1] CRAN (R 4.3.1)
 magrittr      2.0.3   2022-03-30 [1] CRAN (R 4.3.0)
 memoise       2.0.1   2021-11-26 [1] CRAN (R 4.3.0)
 mime          0.12    2021-09-28 [1] CRAN (R 4.3.0)
 openssl       2.1.1   2023-09-25 [1] CRAN (R 4.3.1)
 processx      3.8.4   2024-03-16 [1] CRAN (R 4.3.1)
 promises      1.2.1   2023-08-10 [1] CRAN (R 4.3.0)
 ps            1.7.6   2024-01-18 [1] CRAN (R 4.3.1)
 purrr       * 1.0.2   2023-08-10 [1] CRAN (R 4.3.0)
 R6            2.5.1   2021-08-19 [1] CRAN (R 4.3.0)
 rappdirs      0.3.3   2021-01-31 [1] CRAN (R 4.3.0)
 Rcpp          1.0.12  2024-01-09 [1] CRAN (R 4.3.1)
 rlang         1.1.3   2024-01-10 [1] CRAN (R 4.3.1)
 rmarkdown     2.26    2024-03-05 [1] CRAN (R 4.3.1)
 rstudioapi    0.16.0  2024-03-24 [1] CRAN (R 4.3.1)
 sass          0.4.9   2024-03-15 [1] CRAN (R 4.3.1)
 shiny         1.8.1   2024-03-26 [1] CRAN (R 4.3.1)
 shiny.i18n    0.3.0   2023-01-16 [1] CRAN (R 4.3.0)
 sourcetools   0.1.7-1 2023-02-01 [1] CRAN (R 4.3.0)
 stringi       1.8.3   2023-12-11 [1] CRAN (R 4.3.1)
 stringr     * 1.5.1   2023-11-14 [1] CRAN (R 4.3.1)
 sys           3.4.2   2023-05-23 [1] CRAN (R 4.3.0)
 tinytex       0.50    2024-03-16 [1] CRAN (R 4.3.1)
 vctrs         0.6.5   2023-12-01 [1] CRAN (R 4.3.1)
 waiter        0.2.5   2022-01-03 [1] CRAN (R 4.3.0)
 withr         3.0.0   2024-01-16 [1] CRAN (R 4.3.1)
 xfun          0.43    2024-03-25 [1] CRAN (R 4.3.1)
 xtable        1.8-4   2019-04-21 [1] CRAN (R 4.3.0)
 yaml          2.3.8   2023-12-11 [1] CRAN (R 4.3.1)

 [1] /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library

─────────────────────────────────────────────────────────────────────────────────────────────
>

**Comment by smalltiger-moquan** [comment]
Moveover，I have installed the development version

**Comment by calderonsamuel** [comment]
Your sessioninfo output suggests that installing the development version would fix the problem. Are you still getting an error? If so, please paste the error message again

**Comment by calderonsamuel** [comment]
Closing for no having further information
