### ISSUE TITLE
[FR]: save chat history in a json for training

### ISSUE THREAD

**Issue by MichelNivard** [MichelNivard/gptstudio#200]
### What would you like to have?

Hi, good to be back :), in regular use I find that if the (local) models I use sometimes make errors, but then when I tell it it made an error and what the error was, it self corrects. I have had like at least 100-150 conversations like it. I occurs to me these would be excellent for fin tuning the model not to make those mistakes again.

So I want to start saving those to train the local model "overnight". My goals is this loop: use a light local model, help it out when it errors or dreams up packages that do not exist, if it then self corrects based on my feedback save the full conversations. Then when I have ~20-40 conversations fine-tune the model over those overnight, finetune on these convo's directly, but also use LLAMA3 to generate new training data about the functions and packages used in the chats "generate 5 common user questions about 'geom_smooth()' and generate answers to each". This would (hopefully) create an iterative loop where the small model get trained in a a user/task specific manner. I'd use parameter efficient training where it runs on my macbook overnight. 

so what I need from gptstudio:

1. a way to export chats either automatically or with code

Then, and this is a bit of a stretch I know... It would really help this process if when the local model fails i could hit a "get help from the cloud" button, which just would feed the ongoing convo to LLAMA 3, GPT-3 or Claude3 and let it suggest the correct answer.

so what I'd ned from gptstudio

2 a "help me out here" button that falls back to a way stronger model mid chat.

I am currently working on the backend that would extract all functions and packages mentioned in ppl's chats in an anonymity preserving way, and based on those would generate synthetic training data from models in the cloud (LLama 3 and Mixtral), in order to support local user specific training.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MichelNivard** [comment]
Thinking about this more, I might just need to write a separate package for this,  based on the bones on gptstudio...

**Comment by calderonsamuel** [comment]
We have a chat history functionality. We could add an export button for the chat collection or individually. The second one might be out of scope 🤔 I imagine the end goal is to have a better model for working specifcally with R?
