### ISSUE TITLE
[Bug]: gptstudio quits 

### ISSUE THREAD

**Issue by fdepaolis** [MichelNivard/gptstudio#208]
### Confirm setup

- [X] I have installed the development version of `{gptstudio}` (`pak::pak("MichelNivard/gptstudio")`) and tested if the problem remains.
- [X] I have installed the `{reprex}` and `{sessioninfo}` packages to be able to run this issue's code snippet `pak::pak(c("reprex", "sessioninfo"))`.

### What happened?

I was trying to run ChatGPT from Addins, when it unexpectedly crashed and closed itself even before I was able to type any prompts

### Relevant log output

```shell
library(readr)
vector_variables <- read_csv("odrive/OneDrive MIDD/_!!__CLASSES/8500_Policy&DataAnalytics/Data & Dictionaries/_Dev Data/2024 clean/vector-variables.csv")
View(vector_variables)
clean_data <- purrr::map2(Country_Data, vector_variables, dplyr::select)
clean_data <- purrr::map2(Country_Data, vector_variables$`Variable Name`, dplyr::select)
View(Country_Data)
names.use <- names(df)[!(names(df) %in% f)]
names.use <- names(Country_Data)[!(names(Country_Data) %in% vector_variables$`Variable Name`)]
names.use <- names(Country_Data)[!(names(Country_Data) %in% vector_variables$`Variable Name`)]
Country_Data.subset <- Country_Data[, names.use]
View(Country_Data.subset)
names.use
a <- names(County_Data)
a <- names(Country_Data)
b <- vector_variables$`Variable Name`
setdiff(a, b)
setdiff(b, a)
library(readr)
Country_Data <- read_csv("odrive/OneDrive MIDD/_!!__CLASSES/8500_Policy&DataAnalytics/Data & Dictionaries/_Dev Data/2024 clean/Country_Data_Base.csv")
View(Country_Data_Base)
save(Country_Data)
save(Country_Data, file=Country_Data.rda)
save(Country_Data, file="Country_Data.rda")
getwd()
class(Country_Data)
library(Rcmdr)
library(ggfortify)
AirPassengers <- bb1
library(vars)
data(Canada)
autoplot(Canada)
autoplot(Canada, facets = FALSE)
library(xts)
autoplot(as.xts(AirPassengers), ts.colour = 'forestgreen')
library(timeSeries)
autoplot(as.timeSeries(AirPassengers), ts.colour = ('dodgerblue3'))
autoplot(AirPassengers, ts.geom = 'bar', fill = 'cadetblue')
autoplot(AirPassengers, ts.geom = 'ribbon', fill = 'darkgreen')
autoplot(AirPassengers, ts.geom = 'point', shape = 5)
mts <- ts(data.frame(a = c(1, 2, 3, 4, 4, 3), b = c(3, 2, 3, 2, 2, 1)), start = 2010)
autoplot(mts, ts.geom = 'bar', facets = FALSE)
autoplot(mts, ts.geom = 'bar', facets = FALSE, stacked = TRUE)
autoplot(mts, ts.geom = 'ribbon', facets = FALSE)
autoplot(mts, ts.geom = 'ribbon', facets = FALSE, stacked = TRUE)
library(forecast)
d.arima <- auto.arima(AirPassengers)
d.forecast <- forecast(d.arima, level = c(95), h = 50)
autoplot(d.forecast)
autoplot(d.forecast, ts.colour = 'firebrick1', predict.colour = 'red',
predict.linetype = 'dashed', conf.int = FALSE)
getwd()
names(Country_Data_Reduced)
attach(Country_Data_Reduced)
cor(GDP.cap, Infant.Mort)
XICOR::xicor(GDP.cap, Infant.Mort)
corr(GDP.cap, Infant.Mort)
plot(GDP.cap~Infant.Mort)
cor(GDP.cap, Infant.Mort, method = c("pearson"))
cor.test(GDP.cap, Infant.Mort, method = c("pearson"))
cor.test(GDP.cap, Infant.Mort, method = "pearson")
cor(GDP.cap, Infant.Mort, method = "pearson")
cor(GDP.cap, Infant.Mort, use='pairwise.complete.obs')
Scatter_Matrix
library(ggplot2)
library(GGally)
Scatter_Matrix <- ggpairs(Country_Data_Reduced,columns = c(1, 3:6),
title = "Scatter Plot Matrix ",
axisLabels = "show")
library(ggplot2)
library(GGally)
Scatter_Matrix <- ggpairs(Country_Data_Reduced,columns = c(15, 5:8),
title = "Scatter Plot Matrix ",
axisLabels = "show")
Scatter_Matrix
pairs(Country_Data_Reduced[, c(15, 5:8)], main = "Scatter Plot Matrix for mtcars Dataset")
pairs(Country_Data_Reduced[, c(12, 5:8)], main = "Scatter Plot Matrix for mtcars Dataset")
Scatter_Matrix <- ggpairs(Country_Data_Reduced,columns = c(12, 5:8),
title = "Scatter Plot Matrix ",
axisLabels = "show")
#ggsave("Scatter plot matrix.png", Scatter_Matrix, width = 7, height = 7, units = "in")
Scatter_Matrix
cor(GDP.cap, Fem.Lit.Rate, use='pairwise.complete.obs')
XICOR::xicor(GDP.cap, Fem.Lit.Rate)
cor(Urban.pop, Infant.Mort, use='pairwise.complete.obs')
XICOR::xicor(Urban.pop, Infant.Mort)
install.packages("survival")
library(data.table)
a <- USA_Housing_Permits$DATE
library(forecast)
library(ggplot2)
library(tseries)
library(stats)
# For demonstration, we'll generate a simple non-stationary dataset
set.seed(42)
# Generate a non-stationary time series with a trend and seasonality
t <- 1:100
seasonal_component <- 10 * sin(0.2 * t)
trend_component <- 0.5 * t
noise <- rnorm(100, 0, 2)
data <- seasonal_component + trend_component + noise
# Create a data frame from the dataset
df <- data.frame(Data = data)
# Plot the original time series data
ggplot(df, aes(x = 1:nrow(df), y = Data)) +
geom_line() +
labs(x = "Time", y = "Value", title = "Non-Stationary Time Series Data")
# Check for stationarity using Augmented Dickey-Fuller test
adf_test <- function(series) {
result <- adf.test(series)
print(paste("ADF Statistic:", result$statistic))
print(paste("p-value:", result$p.value))
print("Critical Values:")
print(result$critical.values)
}
adf_test(df$Data)
# Differencing to make the time series stationary
df$Differenced_Data <- c(NA, diff(df$Data))
df <- na.omit(df)
# Plot the differenced time series data
ggplot(df, aes(x = 1:nrow(df), y = Differenced_Data)) +
geom_line() +
labs(x = "Time", y = "Value", title = "Stationary Time Series Data")
# ACF and PACF plots for determining ARIMA orders
acf(df$Differenced_Data, lag.max = 20)
title("ACF Plot")
pacf(df$Differenced_Data, lag.max = 20)
title("PACF Plot")
# Split the data into training and testing sets
train_size <- floor(0.8 * nrow(df))
train <- df$Differenced_Data[1:train_size]
test <- df$Differenced_Data[(train_size + 1):nrow(df)]
# Fit an ARIMA model to the training data
model <- arima(train, order = c(1, 1, 1))
# Forecast the test data
forecast <- forecast(model, h = length(test))
# Calculate prediction intervals
residuals <- test - forecast$mean
prediction_interval <- 1.96 * sd(residuals) # 1.96 for a 95% prediction interval
# Plot the forecasts and the actual values with prediction intervals
plot(forecast, include.mean = FALSE, main = "ARIMA Forecasting with Prediction Intervals")
lines(test, col = "blue")
polygon(c(1:length(test), length(test):1), c(forecast$lower, rev(forecast$upper)), col = "pink", border = NA)
install.packages("xlcharts")
library(xlcharts)
reticulate::install_miniconda()
xlcharts::install_openpyxl()
s
library(xlcharts)
treeData <- data.frame(
"Type" = c("Maple", "Oak", "Pine"),
"LeafColor" = c("Red", "Green", "Green"),
"Height" = c(549, 783, 1204)
)
write_xlsx(x = treeData, path = "treeData.xlsx")
wb <- load_workbook(filename = "treeData.xlsx")
ws <- wb |> active()
ws[["C2"]]$value <- 550
ws[["C2"]]$value
colC <- ws[["C"]]
col_range = ws[["C:D"]]
row10 <- ws[[10]]
ws$dimensions
colC <- ws[["C"]]
col_range = ws[["C:D"]]
row10 <- ws[[10]]
ws$dimensions
data <- Reference(ws, min_col = 3, min_row = 2, max_row = 4, max_col = 3)
categories <- Reference(ws, min_col = 1, min_row = 2, max_row = 4, max_col = 1)
chart <- BarChart(
type = "bar",
title = "Tree Height",
legend = NULL
) |>
x_axis(title = "Height (cm)") |>
y_axis(title = "Tree Type")
chart |>
add_data(data = data) |>
set_categories(labels = categories)
ws |> add_chart(chart, anchor = "E1")
wb |> save_workbook("treeData.xlsx")
treeData <- data.frame(
"Type" = c("Maple", "Oak", "Pine"),
"LeafColor" = c("Red", "Green", "Green"),
"Height" = c(549, 783, 1204)
)
treeData <- data.frame(
"Type" = c("Maple", "Oak", "Pine"),
"LeafColor" = c("Red", "Green", "Green"),
"Height" = c(549, 783, 1204)
)
write_xlsx(x = treeData, path = "treeData.xlsx")
wb <- load_workbook(filename = "treeData.xlsx")
ws <- wb |> active()
ws[["C2"]]$value <- 550
ws[["C2"]]$value
colC <- ws[["C"]]
col_range = ws[["C:D"]]
row10 <- ws[[10]]
ws$dimensions
data <- Reference(ws, min_col = 3, min_row = 2, max_row = 4, max_col = 3)
categories <- Reference(ws, min_col = 1, min_row = 2, max_row = 4, max_col = 1)
chart <- BarChart(
type = "bar",
title = "Tree Height",
legend = NULL
) |>
x_axis(title = "Height (cm)") |>
y_axis(title = "Tree Type")
chart |>
add_data(data = data) |>
set_categories(labels = categories)
ws |> add_chart(chart, anchor = "E1")
wb |> save_workbook("treeData.xlsx")
remotes::install_github("mlverse/chattr")
chattr::chattr_app()
chattr_use("gpt4o")
chattr_use("gpt35")
chattr::chattr_use("gpt4o")
library(chattr)
chattr::chattr_use("gpt4o")
chattr::chattr_use("gpt35")
chattr_app()
chattr::chattr_use("gpt35")
chattr_app()
library(chattr)
data(mtcars)
data(iris)
chattr_use("gpt4")
chattr(preview = TRUE)
chattr(preview = TRUE)
chattr_use("gpt35")
chattr_app()
chattr_app()
library(chattr)
chattr_app()
chattr_use("gpt35")
chattr_app()
install.packages("pak")
pak::pac("usethis")
pak::pak("usethis")
pak::pak("usethis")
pak::pak("gptstudio")
usethis::edit_r_environ()
Sys.getenv("OPENAI_API_KEY")
usethis::edit_r_environ()
Sys.getenv("OPENAI_API_KEY")
Sys.getenv("OPENAI_API")
Sys.getenv()
usethis::edit_r_environ()
Sys.getenv()
chattr:::chattr_app()
chattr_use("gpt35")
## insert this in the prompt
library(chattr)
chattr_use("gpt35")
chattr_app()
chattr:::chattr_app()
gptstudio::addin_chatgpt()
gptstudio::addin_chatgpt()
uninstall.packages("chattr")
uninstall.package("chattr")
remove.packages("chattr")
Sys.getenv("OPENAI_API_KEY")
gptstudio::addin_chatgpt()
gptstudio:::addin_chatgpt()
gptstudio
gptstudio()
library(gptstudio)
gptstudio:::addin_chatgpt()
usethis::use_tidy_description()
library(usethis)
usethis::use_tidy_description()
usethis::use_github_action('check-standard')
usethis::use_github_action('check-standard')
pak::pak("MichelNivard/gptstudio")
Sys.getenv("OPENAI_API_KEY")
gptstudio::chat
gptstudio::chat()
gptstudio::addin_chatgpt()
library(gptstudio)
gptstudio::addin_chatgpt()
gptstudio:::gptstudio_chat()
gptstudio:::gptstudio_chat()
gptstudio::addin_chatgpt()
library(gptstudio)
gptstudio::addin_chatgpt()
install.packages(c("survival", "tseries"))
install.packages("pak")
pak::pak("MichelNivard/gptstudio")
require(usethis)
edit_r_environ()
gptstudio::addin_chatgpt()
install.packages("gptstudio")
gptstudio::addin_chatgpt()
gptstudio:::addin_chatgpt()
pak::pak("MichelNivard/gptstudio")
library(gptstudio)
gptstudio:::addin_chatgpt()
detach("package:gptstudio", unload = TRUE)
gptstudio:::gptstudio_chat()
remove.packages("gptstudio")
install.packages("gptstudio")
library(gptstudio)
gptstudio:::addin_chatgpt()



Loading required package: shiny

Listening on http://127.0.0.1:6734
Not chat history found.
Warning: Error in purrr::map_chr: ℹ In index: 1.
Caused by error:
! Result must be length 1, not 0.
  80: <Anonymous>
  79: signalCondition
  78: signal_abort
  77: rlang::abort
  76: cli::cli_abort
  75: h
  74: .handleSimpleError
  73: call_with_cleanup
  70: map_
  69: purrr::map_chr
  68: %>%
  67: get_available_models
  66: <reactive>
  50: models
  48: observe
  47: <observer>
   4: shiny::runApp
   3: eval
   2: eval
   1: .rs.sourceWithProgress
Deleting chat history from this session.
```

### Session info

```r
gptstudio::gptstudio_sitrep()
#> Error: 'gptstudio_sitrep' is not an exported object from 'namespace:gptstudio'
Created on 2024-05-14 with reprex v2.1.0

Session info
sessioninfo::session_info()
#> ─ Session info ───────────────────────────────────────────────────────────────
#>  setting  value
#>  version  R version 4.4.0 (2024-04-24)
#>  os       macOS Sonoma 14.4.1
#>  system   x86_64, darwin20
#>  ui       X11
#>  language (EN)
#>  collate  en_US.UTF-8
#>  ctype    en_US.UTF-8
#>  tz       America/Los_Angeles
#>  date     2024-05-14
#>  pandoc   3.1.12.2 @ /usr/local/bin/ (via rmarkdown)
#> 
#> ─ Packages ───────────────────────────────────────────────────────────────────
#>  package     * version date (UTC) lib source
#>  assertthat    0.2.1   2019-03-21 [1] CRAN (R 4.3.0)
#>  cli           3.6.2   2023-12-11 [1] CRAN (R 4.4.0)
#>  digest        0.6.35  2024-03-11 [1] CRAN (R 4.4.0)
#>  evaluate      0.23    2023-11-01 [1] CRAN (R 4.4.0)
#>  fastmap       1.1.1   2023-02-24 [1] CRAN (R 4.4.0)
#>  fs            1.6.4   2024-04-25 [1] CRAN (R 4.4.0)
#>  glue          1.7.0   2024-01-09 [1] CRAN (R 4.4.0)
#>  gptstudio     0.3.0   2023-07-11 [1] CRAN (R 4.4.0)
#>  htmltools     0.5.8.1 2024-04-04 [1] CRAN (R 4.4.0)
#>  htmlwidgets   1.6.4   2023-12-06 [1] CRAN (R 4.4.0)
#>  httpuv        1.6.15  2024-03-26 [1] CRAN (R 4.4.0)
#>  knitr         1.46    2024-04-06 [1] CRAN (R 4.4.0)
#>  later         1.3.2   2023-12-06 [1] CRAN (R 4.3.0)
#>  lifecycle     1.0.4   2023-11-07 [1] CRAN (R 4.4.0)
#>  magrittr      2.0.3   2022-03-30 [1] CRAN (R 4.4.0)
#>  mime          0.12    2021-09-28 [1] CRAN (R 4.4.0)
#>  promises      1.3.0   2024-04-05 [1] CRAN (R 4.4.0)
#>  purrr         1.0.2   2023-08-10 [1] CRAN (R 4.4.0)
#>  R.cache       0.16.0  2022-07-21 [1] CRAN (R 4.3.0)
#>  R.methodsS3   1.8.2   2022-06-13 [1] CRAN (R 4.4.0)
#>  R.oo          1.26.0  2024-01-24 [1] CRAN (R 4.4.0)
#>  R.utils       2.12.3  2023-11-18 [1] CRAN (R 4.3.0)
#>  R6            2.5.1   2021-08-19 [1] CRAN (R 4.4.0)
#>  Rcpp          1.0.12  2024-01-09 [1] CRAN (R 4.4.0)
#>  reprex        2.1.0   2024-01-11 [1] CRAN (R 4.3.0)
#>  rlang         1.1.3   2024-01-10 [1] CRAN (R 4.4.0)
#>  rmarkdown     2.26    2024-03-05 [1] CRAN (R 4.4.0)
#>  rstudioapi    0.16.0  2024-03-24 [1] CRAN (R 4.4.0)
#>  sessioninfo   1.2.2   2021-12-06 [1] CRAN (R 4.3.0)
#>  shiny         1.8.1.1 2024-04-02 [1] CRAN (R 4.4.0)
#>  styler        1.10.3  2024-04-07 [1] CRAN (R 4.4.0)
#>  vctrs         0.6.5   2023-12-01 [1] CRAN (R 4.4.0)
#>  withr         3.0.0   2024-01-16 [1] CRAN (R 4.4.0)
#>  xfun          0.43    2024-03-25 [1] CRAN (R 4.4.0)
#>  xtable        1.8-4   2019-04-21 [1] CRAN (R 4.3.0)
#>  yaml          2.3.8   2023-12-11 [1] CRAN (R 4.4.0)
#> 
#>  [1] /Library/Frameworks/R.framework/Versions/4.4-x86_64/Resources/library
#> 
#> ──────────────────────────────────────────────────────────────────────────────
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by calderonsamuel** [comment]
It looks like you got an error when running the CRAN version of the package. Please install the development version with:

```
pak::pak("MichelNivard/gptstudio")
```

In other words, installing this package with `install.packages()` will give you an outdated version until we push a new one into CRAN, which will hopefully happen before the end of this month.

Try it and let us know if that solved the issue

**Comment by fdepaolis** [comment]
Nope….I ran that one too and didn’t work either…any other suggestions?

Thank you


Fernando DePaolis
Middlebury Institute of International Studies

Sent from Outlook for iOS<https://aka.ms/o0ukef>. Apologies for any typos.

________________________________

**Comment by calderonsamuel** [comment]
We need to verify that this issue is ocurring in the development version of the package because this was reported before and fixed. Your code history and session info output are telling us that you are using the CRAN version. Please follow this steps:

1. Install development version: `pak::pak("MichelNivard/gptstudio")`
2. Restart R session (Rstudio > Session > Restart R).
3. Try the addin

If the problem persists, paste the output of `reprex::reprex(gptstudio::gptstudio_sitrep(), session_info = TRUE)` to verify that you are in fact using the development version.

**Comment by fdepaolis** [comment]
I tried the development version (see session info below). This time it didn't shut down...but something else happened. There is no options for settings like in the cran version...and no matter what the question in the prompt, it doesn't provide any answers. It just show the cute robot face.

Thank you for your help.
====


gptstudio::gptstudio_sitrep()
#> 
#> ── Configuration for gptstudio ─────────────────────────────────────────────────
#> No user configuration file found at
#> '/Users/fdepaolis/Library/Preferences/org.R-project.R/R/gptstudio/config.yml'.
#> Using default configuration. Change configuration settings in the chat app.
#> Lauch the chat app with addins or `gptstudio_chat()`.
#> 
#> ── Current Settings ──
#> 
#> - Model: gpt-4-turbo-preview
#> - Task: coding
#> - Language: en
#> - Service: openai
#> - Custom prompt:
#> - Stream: TRUE
#> - Code style: no preference
#> - Skill: beginner
#> 
#> ── Checking API connections ──
#> 
#> ── Checking OpenAI API connection
#> ✔ Successfully connected to the OpenAI API service.
#> 
#> ── Checking HuggingFace API connection
#> ✖ API key is not set or invalid for HuggingFace service.
#> 
#> ── Checking Anthropic API connection
#> ✖ API key is not set or invalid for Anthropic service.
#> 
#> ── Checking Google AI Studio API connection
#> ✖ API key is not set or invalid for Google AI Studio service.
#> 
#> ── Checking Azure OpenAI API connection
#> ✖ API key is not set or invalid for Azure OpenAI service.
#> 
#> ── Checking Perplexity API connection
#> ✖ API key is not set or invalid for Perplexity service.
#> 
#> ── Checking Cohere API connection
#> ✖ API key is not set or invalid for Cohere service.
#> 
#> ── Check Ollama for Local API connection
#> ✖ Couldn't connect to Ollama in <http://localhost:11434>. Is it running there?
#> 
#> ── Getting help ──
#> 
#> See the gptstudio homepage (<https://michelnivard.github.io/gptstudio/>) for
#> getting started guides and package documentation. File an issue or contribute
#> to the package at the GitHub repo
#> (<https://github.com/MichelNivard/gptstudio>).
#> ── End of gptstudio configuration ──────────────────────────────────────────────
Created on 2024-05-15 with [reprex v2.1.0](https://reprex.tidyverse.org/)

Session info
sessioninfo::session_info()
#> ─ Session info ───────────────────────────────────────────────────────────────
#>  setting  value
#>  version  R version 4.4.0 (2024-04-24)
#>  os       macOS Sonoma 14.4.1
#>  system   x86_64, darwin20
#>  ui       X11
#>  language (EN)
#>  collate  en_US.UTF-8
#>  ctype    en_US.UTF-8
#>  tz       America/Los_Angeles
#>  date     2024-05-15
#>  pandoc   3.1.12.2 @ /usr/local/bin/ (via rmarkdown)
#> 
#> ─ Packages ───────────────────────────────────────────────────────────────────
#>  package     * version    date (UTC) lib source
#>  assertthat    0.2.1      2019-03-21 [1] CRAN (R 4.3.0)
#>  cli           3.6.2      2023-12-11 [1] CRAN (R 4.4.0)
#>  curl          5.2.1      2024-03-01 [1] CRAN (R 4.4.0)
#>  digest        0.6.35     2024-03-11 [1] CRAN (R 4.4.0)
#>  evaluate      0.23       2023-11-01 [1] CRAN (R 4.4.0)
#>  fansi         1.0.6      2023-12-08 [1] CRAN (R 4.4.0)
#>  fastmap       1.1.1      2023-02-24 [1] CRAN (R 4.4.0)
#>  fs            1.6.4      2024-04-25 [1] CRAN (R 4.4.0)
#>  glue          1.7.0      2024-01-09 [1] CRAN (R 4.4.0)
#>  gptstudio     0.3.1.9009 2024-05-15 [1] Github (MichelNivard/gptstudio@a6799be)
#>  htmltools     0.5.8.1    2024-04-04 [1] CRAN (R 4.4.0)
#>  htmlwidgets   1.6.4      2023-12-06 [1] CRAN (R 4.4.0)
#>  httpuv        1.6.15     2024-03-26 [1] CRAN (R 4.4.0)
#>  httr2         1.0.1      2024-04-01 [1] CRAN (R 4.4.0)
#>  jsonlite      1.8.8      2023-12-04 [1] CRAN (R 4.4.0)
#>  knitr         1.46       2024-04-06 [1] CRAN (R 4.4.0)
#>  later         1.3.2      2023-12-06 [1] CRAN (R 4.3.0)
#>  lifecycle     1.0.4      2023-11-07 [1] CRAN (R 4.4.0)
#>  magrittr      2.0.3      2022-03-30 [1] CRAN (R 4.4.0)
#>  mime          0.12       2021-09-28 [1] CRAN (R 4.4.0)
#>  pillar        1.9.0      2023-03-22 [1] CRAN (R 4.4.0)
#>  promises      1.3.0      2024-04-05 [1] CRAN (R 4.4.0)
#>  purrr         1.0.2      2023-08-10 [1] CRAN (R 4.4.0)
#>  R.cache       0.16.0     2022-07-21 [1] CRAN (R 4.3.0)
#>  R.methodsS3   1.8.2      2022-06-13 [1] CRAN (R 4.4.0)
#>  R.oo          1.26.0     2024-01-24 [1] CRAN (R 4.4.0)
#>  R.utils       2.12.3     2023-11-18 [1] CRAN (R 4.3.0)
#>  R6            2.5.1      2021-08-19 [1] CRAN (R 4.4.0)
#>  rappdirs      0.3.3      2021-01-31 [1] CRAN (R 4.4.0)
#>  Rcpp          1.0.12     2024-01-09 [1] CRAN (R 4.4.0)
#>  reprex        2.1.0      2024-01-11 [1] CRAN (R 4.3.0)
#>  rlang         1.1.3      2024-01-10 [1] CRAN (R 4.4.0)
#>  rmarkdown     2.26       2024-03-05 [1] CRAN (R 4.4.0)
#>  rstudioapi    0.16.0     2024-03-24 [1] CRAN (R 4.4.0)
#>  sessioninfo   1.2.2      2021-12-06 [1] CRAN (R 4.3.0)
#>  shiny         1.8.1.1    2024-04-02 [1] CRAN (R 4.4.0)
#>  styler        1.10.3     2024-04-07 [1] CRAN (R 4.4.0)
#>  utf8          1.2.4      2023-10-22 [1] CRAN (R 4.4.0)
#>  vctrs         0.6.5      2023-12-01 [1] CRAN (R 4.4.0)
#>  withr         3.0.0      2024-01-16 [1] CRAN (R 4.4.0)
#>  xfun          0.43       2024-03-25 [1] CRAN (R 4.4.0)
#>  xtable        1.8-4      2019-04-21 [1] CRAN (R 4.3.0)
#>  yaml          2.3.8      2023-12-11 [1] CRAN (R 4.4.0)
#> 
#>  [1] /Library/Frameworks/R.framework/Versions/4.4-x86_64/Resources/library
#> 
#> ──────────────────────────────────────────────────────────────────────────────

**Comment by calderonsamuel** [comment]
Ok. The settings are in the sidebar panel. You can open it clicking the `<` button at the top left. 

We can confirm that you are using a valid API KEY. We could be having two other problems:

1. You might not have credits in your OpenAI account
2. You might not be able to connect to the API for network issues, such as firewalls or proxy setup

When the gptstudio chat starts, Rstudio should show a "Background jobs" panel (which are background R processes). Please enter the gptstudio job and copy the output you see when sending a prompt to the chat. You might find relevant warnings or messages there.

**Comment by fdepaolis** [comment]
Thank you.

  1.  I am using a valid API KEY
  2.  The setting gear icon is grayed out and it doesn’t lead anywhere when I click on it.
  3.  It wasn’t clear that (anywhere) that I couldn’t use a free account…so no, I don’t have available credits
  4.  No firewalls or proxy setup

Thank you…that’s all for now…I’ll try a few more things on my own from here on…
I really appreciate your help



Fernando DePaolis, Ph.D.
Environmental Policy & Management Program<https://www.middlebury.edu/institute/academics/degree-programs/environmental-policy-management>
Middlebury Institute of International Studies<http://www.middlebury.edu/institute> at Monterey
----------------------------------------------------------------------
[Sent from Outlook for Mac]
My working hours (US Pacific time zone) may not be your working hours. Please do not feel obligated to respond outside your normal work hours.




From: Samuel Calderon ***@***.***>
Date: Wednesday, May 15, 2024 at 3:05 PM
To: MichelNivard/gptstudio ***@***.***>
Cc: DePaolis, Fernando ***@***.***>, Author ***@***.***>
Subject: Re: [MichelNivard/gptstudio] [Bug]: gptstudio quits (Issue #208)

Ok. The settings are in the sidebar panel. You can open it clicking the < button at the top left.

We can confirm that you are using a valid API KEY. We could be having two other problems:

  1.  You might not have credits in your OpenAI account
  2.  You might not be able to connect to the API for network issues, such as firewalls or proxy setup

When the gptstudio chat starts, Rstudio should show a "Background jobs" panel (which are background R processes). Please enter the gptstudio job and copy the output you see when sending a prompt to the chat. You might find relevant warnings or messages there.

**Comment by JamesHWade** [comment]
Closing for now. Please reopen if you run into more issues.

**Comment by fdepaolis** [comment]
Thank you.

Fernando DePaolis
Middlebury Institute of International Studies

Sent from Outlook for iOS<https://aka.ms/o0ukef>. Apologies for any typos.

________________________________
