### ISSUE TITLE
issue running gptstudio with ollama

### ISSUE THREAD

**Issue by jakeberv** [MichelNivard/gptstudio#212]
Hi there-- 
I'm trying to get gptstudio working with codestral and ollama -- 
I have managed to get local ollama working with the new codestral model (not using docker). using the development version of gptstudio, the shiny chat works (after setting the local api), but it seems like the other addins (commenting etc) are defaulting to using ChatGPT and not the local ollama instance. Is there any obvious thing to try? 

Thanks,
Jake

**Comment by calderonsamuel** [comment]
Thanks for your report @jakeberv ! 

We need more information about your setup to correctly diagnose the problem, please open a new issue following the "Bug report" route. We provide instructions for sharing setup information there. I'll close this issue but hope to continue this thread on the new issue.
