### ISSUE TITLE
Set gpt4o mini as default for openai

### ISSUE THREAD

**Issue by calderonsamuel** [MichelNivard/gptstudio#219]
### What would you like to have?

Support for text and vision capabilities. https://openai.com/index/gpt-4o-mini-advancing-cost-efficient-intelligence/

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JamesHWade** [comment]
Should already be there, no?

<img width="337" alt="image" src="https://github.com/user-attachments/assets/01c8f3da-1bad-43eb-bd0b-b48f236becb7">

**Comment by calderonsamuel** [comment]
You're right! But I think it should be the new default + we should support vision now (maybe track it in another ticket). WDYT?

**Comment by JamesHWade** [comment]
Great idea to make it the default. Vision support will take some work. I say we break that out into a separate issue.

**Comment by calderonsamuel** [comment]
We will track vision support in #222
