### ISSUE TITLE
[FR]: Time to migrate from magrittr %>% to base pipe |>?

### ISSUE THREAD

**Issue by JamesHWade** [MichelNivard/gptstudio#225]
### What would you like to have?

R 4.1 was released over 3 years ago. Should we migrate to base pipe?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by calderonsamuel** [comment]
I'm ok with this. We already have some calls of the base pipe in the source code.

https://github.com/search?q=repo%3AMichelNivard%2Fgptstudio+%7C%3E+path%3A%2F%5ER%5C%2F%2F&type=code

But let's first close the current open PR before start work on this
