### ISSUE TITLE
Dialog in a quarto doc?

### ISSUE THREAD

**Issue by MichelNivard** [MichelNivard/gptstudio#25]
This works in terms of OpenAi playing ball, we just need to figure out whether we can get the document context out of the rstudioapi and on click present the entire doc and, when it is returned, restore the convo, or only add the new text, and the Q: prompt to the bottom of the doc... 

https://user-images.githubusercontent.com/11858442/210117832-cd935bb0-d144-4b86-b412-39edad476464.mov

**Comment by JamesHWade** [comment]
#28 ready for testing!

https://user-images.githubusercontent.com/6314313/210177908-7cf0f991-54f2-4f96-8bcd-3077bc8bbb25.mov
