### ISSUE TITLE
bugs and strategy?

### ISSUE THREAD

**Issue by MichelNivard** [MichelNivard/gptstudio#31]
@JamesHWade  new way of handling the API ingestion (great!) doesn't work for the model builder it seems and 2 I tried and failed to open a chat in quarto and now RStudio can't in any way open a new Quarto doc anymore (even in other projects) and gives an error that says "state is unrecoverable". So maybe we should move the chat to a dev branch? I think Aden brake is a good idea anyway as we won't have time to respond quickly to breaks once our full time jobs pick up steam... how about we move chat to a dev and keep the relatively stable pieces on main?

**Comment by MichelNivard** [comment]
error on the model editor: Warning: Error in create_completion: argument "openai_api_key" is missing, with no default

**Comment by MichelNivard** [comment]
That specific error was my Mac M2 not being able to run quarto or panic I think, and while other programs would prompt me to install, this didnt.. som maybe "not an us problem"...

**Comment by JamesHWade** [comment]
Yeah, definitely a good idea for us to have a dev branch for very new fixes.. The quarto error is weird... we don't actually do anything with quarto other than ask the user to install the quarto package if they don't have it. I can do a little more testing to see if I can recreate.

For the missing API... I think I know what caused that. I'll work on a fix.

**Comment by JamesHWade** [comment]
I'll work on better testing this week to catch simple errors before we push new features. We have tests, but the dependency on an external API makes them a little harder to write well.

**Comment by MichelNivard** [comment]
yeah quarto was a very specific thing about a new machine, turns out quarto and panda aren't native to the new Mac CPU architecture and I had to installed the tralnslation layer for software designed for the old CPU architecture...

**Comment by jmouchnino** [comment]
> error on the model editor: Warning: Error in create_completion: argument "openai_api_key" is missing, with no default

I get the same error. 

I use an R script and not a RMarkdown/Quarto file. May it explain the error?

**Comment by JamesHWade** [comment]
Ah, that looks like it's just a bug. I pushed some cleaner (though probably still buggy) code not too long ago. Do you mind updating and trying again @jmouchnino ?
