### ISSUE TITLE
openai_chat() not producing expected behaviour

### ISSUE THREAD

**Issue by tspeidel** [MichelNivard/gptstudio#36]
I installed the library without any issues. When I test the `gptstudio:::openai_chat()` functionality, the answer I get through the API does not make sense.  For example, reproducing the readme example gives me the following:

```
Question: what are your top 3 tips for learning R?
The answer to your question depends on the specific context in which it is asked. Without more information, it is difficult to provide an accurate answer.
```

I can reproduce the behaviour with other questions:

```
Question: who's the current Canadian prime minister?
There is no single answer to this question as it depends on the specific context and situation. Generally speaking, the best way to handle a difficult situation is to remain calm, listen to all parties involved, and find a solution that is acceptable to everyone. It is also important to be respectful and open-minded when discussing the issue. Additionally, it is important to consider the long-term consequences of any decision that is made.
```

Am I missing something?

```
R version 4.2.1 (2022-06-23 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19044)
gptstudio_0.1.2
```

**Comment by JamesHWade** [comment]
Hmmm... I don't think you are missing anything, but I'm confused as to what might be going on. Can you try out any of the other addins to see if they are working?

What version of `rstudioapi` are you using? You should be able to get that with `packageVersion("rstudioapi")`.

**Comment by tspeidel** [comment]
I'm using v. 0.14 of `rstudioapi`

Here's what I tested so far:
Spelling & Grammar: works as expected
Change text to active voice: works as expected
Write code from prompt: works as expected

**Comment by JamesHWade** [comment]
Well, I'm flummoxed. I will do some troubleshooting to see if I can find a fix. I'm not able to replicate, so it's a bit hard for me to offer advice. 🤷‍♂️

I'll leave the issue open in case others have ideas.

**Comment by tspeidel** [comment]
Thanks for making those changes. Still no luck :-(
I've upgraded R, updated all packages, reinstalled gptstudio. None helped.
I'm going to try regenerating a new API key.

Is there a manual way to submit a question to chatGPT without using Quarto and the addin?

**Comment by tspeidel** [comment]
Bingo! 
Ok, it's a bit embarrassing to say, but what I needed to do is to manually save the qmd before submitting. For whatever reason, the qmd does not save by itself and therefore it is indeed sending an empty query to chatGPT. 

I have two suggestions. (1) consider implementing an autosave of the qmd before execution of the call or, alternatively, (2) in the video tutorial make it clear to click save everytime the qmd changes.

**Comment by JamesHWade** [comment]
Not embarrassing at all. I'll see if I can check for that with the `rstudioapi`. My files autosave from my global configuration, but that's not enabled by default. Thanks for the follow up!
