### ISSUE TITLE
Doesnt work for my specific RStudio configuration

### ISSUE THREAD

**Issue by kondofersky** [MichelNivard/gptstudio#38]
Hi,

thank you very much for the package. So far, I could install it and tried to use it with a valid API key. The problem is that I get errors, which I think are connected to my specific RStudio configuration. I am using rstudio-server 1.3.959 with R version 4.0.0. 

The problem is that I cannot install a newer version of R or rstudio-server because my linux server on which I am running my system is old and currently can't be updated.

Do you know of any way I can run your package on a bit older version like mine? Or maybe the versions aren't the issues and I am missing something else?

Thanks!

P.S. here are some of the errors I am getting:
GPT Chat: Error: Function documentPath not found in RStudio
Freeform editor: Error in withr::local_options(shiny.launch.browser = .rs.invokeShinyPaneViewer) : 
  unused argument (shiny.launch.browser = .rs.invokeShinyPaneViewer)
Spelling and Grammar: Error: Function selectionGet not found in RStudio
Comment your code: Error: Function selectionGet not found in RStudio

**Comment by JamesHWade** [comment]
I'll close for now, but let me know if you aren't able to get those functions to work.
