### ISSUE TITLE
"API key not found or is not formatted correctly" Error 

### ISSUE THREAD

**Issue by mattiaginoble** [MichelNivard/gptstudio#39]
Hello,
I'm trying to set the API Key, but I retrieved this error in R studio's console.
"API key not found or is not formatted correctly"

R studio is up to date, but I can't figure out.

Can you help me please?

Thanks
Mattia

**Comment by JamesHWade** [comment]
What is the output of you load the package and run this?

```
library(gptstudio)
check_api()
```

**Comment by mattiaginoble** [comment]
Checking API key using OPENAI_API_KEY environment variable...
! OPENAI_API_KEY is not set.
Do you want to set the OPENAI_API_KEY for this session?

1: No
2: Negative
3: Yup

**Comment by MichelNivard** [comment]
Make sure the API key doesnt have quotes around it (this has happened to me
a few times).

**Comment by mattiaginoble** [comment]
there are not any quotes, I don't know why gives me this error

**Comment by JamesHWade** [comment]
Maybe check the output of Sys.getenv("OPENAI_API_KEY")? If you don't see your API key there, that means it has not been set.

**Comment by mattiaginoble** [comment]
there is no api key set, how can I set ? because I get these error every time I try to insert my one

**Comment by MichelNivard** [comment]
You can try setting it manually: Sys.setenv(OPENAI_API_KEY = "<APIKEY>")
 where you place your api key in place of <APIKEY>

**Comment by mattiaginoble** [comment]
I have already followed the whole guide on the page for, including this step to enter the key.
Anyway after I enter this command I have no error, but the moment I start the chatGPT this asks me again for the key, and after inserits it gives me the above error, asking me quinid to enter it again

**Comment by mattiaginoble** [comment]
I tried again to enter with this command, and now it is working.
Thank you very much for your help, I don't know what happened yesterday.

**Comment by JamesHWade** [comment]
Glad it's working for you! Feel free to re-open this issue if the problem happens again.
