### ISSUE TITLE
Error message with "create_gpt_chat()"

### ISSUE THREAD

**Issue by hwangQ** [MichelNivard/gptstudio#40]
Hello~

Whenever I excute create_gpt_chat() function I see an error message as such:

> gptstudio:::create_gpt_chat()
Error in `Encoding<-`(`*tmp*`, value = "UTF-8") : 
  a character vector argument expected

Could you please let me know how I can resolve this issue? Thanks!

Best, 
Hwanggyu

**Comment by JamesHWade** [comment]
It looks like you found a bug. I'll need to mess with encodings for users who don't use UTF-8 as their default. Thanks for reporting this.

**Comment by hwangQ** [comment]
I am glad that I can help you to improve the pakcage. Please let me know once you fixed the bug. Thanks!

Best, 
Hwanggyu

**Comment by JamesHWade** [comment]
I pushed some changes that _may_ fix it, but I don't have a good way to reproduce the error locally. Please let me know if this fixed it for you.

**Comment by hwangQ** [comment]
Thanks for quickly responding to this issue. Unfortunately, the updated code does not work. It returned the same error message:

> gptstudio:::create_gpt_chat()
Error in `Encoding<-`(`*tmp*`, value = "UTF-8") : 
  a character vector argument expected

I digged this issue a litter further. I see that the error message was returned when running `rstudioapi::documentPath()` function. The script of this function is:

> rstudioapi::documentPath
function (id = NULL) 
{
    path <- callFun("documentPath", id = id)
    Encoding(path) <- "UTF-8"
    path
}

When running the script of the this function:
> path <- callFun("documentPath", id = NULL)
> Encoding(path) <- "UTF-8"
Error in `Encoding<-`(`*tmp*`, value = "UTF-8") : 
  a character vector argument expected

I see the same error message with as above. Do you have any idea to figure this issue out, if any? Thank you!

**Comment by hwangQ** [comment]
I figured out this issue by excuting "gptstudio:::create_gpt_chat()" in the saved document (test_ai.R) as you can see in the screenshot below:

![image](https://user-images.githubusercontent.com/43680218/213168187-a0296072-de0b-46c3-8eef-196263879b66.png)

However, the error messgae was returned when running the same function in the unsaved document as below:

![image](https://user-images.githubusercontent.com/43680218/213168769-187051a2-0ecc-434b-852c-11b966dc3232.png)

I am not sure why this happend with unsaved document. 

In addition, I found two more issues in my R studio. First, "Start GPT Chat" is now shown in Addins as below: 

![image](https://user-images.githubusercontent.com/43680218/213169226-8e640156-0c80-428e-8ddc-628916ab695a.png)

Second, whenever running "GPT Chat" in Addins to chat with GPT, it excuted "gptstudio:::run_gpt_chat()", not "gptstudio:::run_gpt_chat()". So, it returns an error message as you can see below:

![image](https://user-images.githubusercontent.com/43680218/213169592-441cf8e6-dfd5-4920-b64f-6641fa935d6c.png)

Thanks!

**Comment by JamesHWade** [comment]
The very latest version on GitHub should now open a shiny app instead of the quarto doc. @MichelNivard wisely pointed out that a quarto dependency is not the best idea. Can you give that a shot and let me know if it works?

**Comment by hwangQ** [comment]
Thanks!, However, I've alreadly installed the lasted version (v 0.1.2). When selecting "GPT chat" in Addis to start chat with GPT, it still gives me the same error message:

> gptstudio:::run_gpt_chat()
Error: object 'run_gpt_chat' not found

Is there any other way that I can try to open a shiny app?

**Comment by JamesHWade** [comment]
Correct you are. I am pushing an updated version (0.1.3) now.

**Comment by hwangQ** [comment]
Awesome! I will try with the newest version once it is released.

**Comment by hwangQ** [comment]
The new version works well with a shiny app. Thanks!
