### ISSUE TITLE
Add tests for GPT chat functions

### ISSUE THREAD

**Issue by JamesHWade** [MichelNivard/gptstudio#42]
The function in `chat_gpt.R` are tedious to test since they depend on `{rstudioapi}`. Nonetheless, we need some unit tests for this code since it is likely to be a popular feature of the package.

**Comment by MichelNivard** [comment]
Why if we move chat to a shiny app in the viewer pane? Seems like it would be less likely to break due to people manually modifying or moving chat files? Just keep a text box for consecutive questions on the bottom and fill the rest of the app with a scrollable text field that grows and updates per Q? Also gets rid of the quatro dependency

**Comment by JamesHWade** [comment]
I like that. I had initially used the quarto doc because I liked saving the model responses, but we could always have a "generate quarto doc" button.

**Comment by MichelNivard** [comment]
I want to work towards saving a summary of the conversation,and making it an option to propt the next conversation with "This is an ongoing conversation we have previously discussed: <SUMMMARIES>" so the chat has som kind of "memory". Have been playing around with that manually and it makes the chat feel more familiar. anyway yes an export button, and a resume button that searched for a standard filename would be enough

**Comment by MichelNivard** [comment]
been playing around with the shiny app, its amazing! may try and tweak the UI a bit to converge on something similar to openAi's design (Chet history up top, text input at the bottom)... have to try and figure out whether we can add "Respons in markdown" to the prompt and then parse markdown to make any code etc in awnsers into code blocks? would depend in how well it writes markdown...

**Comment by JamesHWade** [comment]
Testing is better but not perfect. Closing for now.
