### ISSUE TITLE
Error for gptstudio in Rstudio

### ISSUE THREAD

**Issue by AtharKharal** [MichelNivard/gptstudio#45]
Following is my interaction. How can I fix it. Thanx

gptstudio:::chat_gpt_addin()
✔ API already validated in this session.
Error: 'card' is not an exported object from 'namespace:bslib'

**Comment by JamesHWade** [comment]
What version of bslib are you using? It should be in the namespace, so I'm a bit confused by the error.

**Comment by AtharKharal** [comment]
Yes the package had to be updated and now it is fixed. Thanx
