### ISSUE TITLE
Switch over to the new model?

### ISSUE THREAD

**Issue by MichelNivard** [MichelNivard/gptstudio#46]
@JamesHWade I think we should switch over asap? See for description: https://openai.com/blog/introducing-chatgpt-and-whisper-apis

**Comment by JamesHWade** [comment]
Already working on it :)

**Comment by MichelNivard** [comment]
Awesome, so no need for me to start on gptstudio?

**Comment by JamesHWade** [comment]
I have a (minimal) integration for gpttools. Now implement for gptstudio. 

https://github.com/JamesHWade/gpttools/pull/35
