### ISSUE TITLE
Start GPT Chat Missing

### ISSUE THREAD

**Issue by JoeFernando** [MichelNivard/gptstudio#49]
Thanks for this library, looks very interesting.

I installed the library but "Start GPT Chat" is not there under "Addins", all other functions are there....am i missing something?

**Comment by JamesHWade** [comment]
Are you still having this issue? It should say "GPT Chat" under Addins. If not, are any of the gptstudio addins showing up for you?

**Comment by JamesHWade** [comment]
Will be addressed once #52 is complete.
