### ISSUE TITLE
Coordination

### ISSUE THREAD

**Issue by MichelNivard** [MichelNivard/gptstudio#5]
@JamesHWade These are some ideas for ways we can go forward with this project, prompted by your new addin.

so it occurred to me the list of potential addins could quickly escalate (in a good way). One way to go about managing this is a coordinated split:

**gptstudio** general set of addins for coding/writing in Rstudio. Spelling, generate text/code from prompt, comment code, etc.

**gpttools** addins meant to help package/function development in r. The exciting part hee is that it would be relatively easy (I think) to tune OpenAI models to specific task like writing a manual page, making a script into a function. For me it would be exciting to see if I could tune model for this.

**gptmodels** this is still a vague notion but a set of addins to help people 1. Suggest models to analyze data 2. Explain existing models to them 3. List assumptions of highlighted models etc… this has huge “helping people get in way over their heads” potential…

all three could share a common free form editor, basics usage, but allow for user opt-in for bunched of 3-6 addins to avoid addin menu clutter. Maybe downstream this structure also allows for easy experimenting with custom tuned versions of the GPT models these use. Reason I opens this for discussion is that this split would require you to take the lead on some of this, because how would I know what addins work well for developers right?

**Comment by JamesHWade** [comment]
Great idea! I'll do some exploring to see if it makes sense to keep these in the same package or break out into a family of packages. My hunch is that smaller related packages will be easier to maintain in the long run.

**Comment by MichelNivard** [comment]
So here is my current thinking on this:

gptstudio (generalist tools, for writing reports, code, websites, analysis etc)

base addins:
text from prompt
code from prompt (going to split this in two because we can then use separate text and code models)
freeform editor.

specific addins:
active writing style (if this is still useful actually now that there is a freeform editor)
spell/grammar check
comment on code

**gpttools** (devtools like, going to honest, this should reside primarily on your github, you should maintian get credit etc, ill happily think along...)

base addins:
text from prompt
code from prompt (going to split this in two because we can then use separate text and code models)
freeform editor.

specific addins:
roxygen
debug (?)
refractor code (?)
style code (?)
script to function (?)


future ideas:

**gpttutor**

base addins

specific addins:
explain code
explain model
etc
etc


**gptmodels**

no idea but help with specifying selecting and assumptions in statistical and inferential models?

let me know what you think, if you agree maybe we could implement the first split coming few days (I cant do that todaty, I have: split "text from prompt" and "code from prompt" on my to-do for today, I need that before I can start to consider tuning an R code specific version of the code model)

**Comment by MichelNivard** [comment]
Or more efficient: one package for general addins, then topic-specific extension pack packages?

**Comment by JamesHWade** [comment]
Okay, before you do a lot of new code editing, let me submit my latest PR. It's got some refactoring that I _think_ will make your life easier to rework prompts.

**Comment by MichelNivard** [comment]
sure no problem!

**Comment by JamesHWade** [comment]
Made some progress create [gpttools](https://github.com/JamesHWade/gpttools). Looks like I forgot to push the latest tests on gptstudio that so you're getting a build error. I'll create a PR now.

**Comment by MichelNivard** [comment]
okay, I lowercased the [gptstudio](https://github.com/MichelNivard/gptstudio) repo to bring things in line. Prob moving this repo into an organization account, still thinking of a name for that current working title: "gptinr" so you'd get gptinr/gpttools and gptinr/gptstudio

**Comment by JamesHWade** [comment]
I like the name!

Are you thinking about bringing in other models outside of OpenAI? I wonder if we may want to do something like "transformers" if we may eventually pull in open source models (e.g., from HuggingFace). `{transformerstudio}` and `transformertools` are a bit long, but the hex sticker opportunities are great 😆

**Comment by MichelNivard** [comment]
“Transformers: rstats in disguise”? Don’t think anyone under 30/35 will get it though. Yeah, I am looking at other models but the issues I see are inference time (other models are slower) and lack of stable/final API. I think a medium term goal for me is to make the model aware of the user’s environment, but do so safely (without sending private or sensitive data to OpenAI), I really would like to train a model on prompts that are:. An annonimized summary of the environment (no data just summaries like mean, mode, variance, variable names, data type etc) + an R question. I’d try this with the current model, keep the top results that run given the actual data/envir. I would train it by generating 100’s of real environments based on public datasets, ask 5-20 standard coding questions run ~10 answers  in the environmentl, keep the once that run errorless, manually pick the “best”. That would be a ~500-5000 example prompt/answer combinations for the tuningset. then we get gtpstudio/gpttools to always include the exact same type of environment summary at the top of each prompt, It’s not unlikely that due to tuning the answers from the tuned model would then be better tailored to the users actual environment/data. Anyway, yeah that could end up requiring other open access models? So maybe a general name for the org account so we get: transformers/gpttools and transformers/gptstudio etc?

**Comment by MichelNivard** [comment]
Closing this and moving to discussion!
