### ISSUE TITLE
CRAN Submission?

### ISSUE THREAD

**Issue by JamesHWade** [MichelNivard/gptstudio#52]
Time to get this thing on CRAN? With so much interest (350 ⭐️s!!!), seems like we need to get this thing onto CRAN for broader distribution. If you agree @MichelNivard, I'd like to do some upkeep prior to the submission.

- [x] Convert all model usage over to gpt-3.5-turbo
- [x] Reduce number of plugins
- [x] Tweak ChatGPT app based on initial user feedback
- [x] Reach minimum threshold for testing (80%?)
- [x] Update documentation (especially readme)

**Comment by MichelNivard** [comment]
Yeah those seem reasonable goals before getting this on CRAN! the tweaks to Chat could be most involved, reducing addins seems easy enough some aren't very functional, and there is a way for users to specify their own freeform chat GPT commands (which we coulfd make that easier? could experiment with instructing uses to write their own inline prompt and using their current text selection as prompt?  like "# Debug the code below; temp = 2; tokens = 200" they select the line hit the freeform add-in and its done?

**Comment by MichelNivard** [comment]
Want to drop the active voice addin, that cut down on the addin's?

**Comment by JamesHWade** [comment]
Closing in favor of #62
