### ISSUE TITLE
Chat GPT not working, problem with bslib

### ISSUE THREAD

**Issue by AlPaRol** [MichelNivard/gptstudio#57]
I am experiencing the following problem:

" v API already validated in this session.
v API key is valid.
i Setting OPENAI_API_KEY environment variable.
i You can set this variable in your .Renviron file.
Error: 'card' is not an exported object from 'namespace:bslib' "

The API key is currently validated: 

" > gptstudio:::addin_chatgpt()
v API already validated in this session. "

Also I can't see the "Start GPT Chat" in the addins menu: 

![image](https://user-images.githubusercontent.com/61295762/224966962-1cc8de71-d1dd-4f92-b7f6-dbb7a88d8a8e.png)

Any suggestion?

**Comment by JamesHWade** [comment]
Thank you for creating an issue! You've spotted two bugs we need to fix.

1. It seems like the `{bslib}` package is a bit old. I've updated the dependencies to require 0.4 or greater. Please reopen this issue if updating bslib package does not work for you.
2. ChatGPT replaces Start GPT Chat, but we haven't updated the readme yet. I'll add that as a task to our prep for CRAN release (#52).
