### ISSUE TITLE
No "Write/code from prompt" addin

### ISSUE THREAD

**Issue by CJHansen89** [MichelNivard/gptstudio#60]
Hi there
Great package - just installed gptstudio, have the addin working for e.g., spelling and commenting, but I don't have the "write/code from prompt" option. 
Any suggestion on why this is?
Thanks!
![image](https://user-images.githubusercontent.com/128041838/225596839-5bd3aaee-97af-47d8-9b6e-b7ce62358910.png)

**Comment by JamesHWade** [comment]
We need to update the readme. We removed that in favor of "ChatGPT in Source," but now I'm thinking that's a confusing name. We should have the readme updated soon (hopefully within a week). Thanks for trying it out!!!

**Comment by JamesHWade** [comment]
Readme is now updated. Please reopen if you still have an issue.
