### ISSUE TITLE
Run Shiny App in Background

### ISSUE THREAD

**Issue by jonthegeek** [MichelNivard/gptstudio#64]
When I select the ChatGPT addin, it launches the shiny app in my main session. I'm not certain how to do this, but it would be preferable if the shiny app could run in the "Background Jobs" tab of RStudio.

Testing out Bard has made me even more interested in the GPT models (I thought *sure* Google would be at least close if not ahead, but they clearly aren't), so I expect to have more requests and hopefully PRs coming soon for you!

**Comment by JamesHWade** [comment]
Here's how I'm setting it to run in the viewer pane:
`withr::local_options(shiny.launch.browser = ".rs.invokeShinyPaneViewer")`

Seems like I should turn that into an option you can specify. I didn't have any luck getting it to actually run as a background job. Once that's figured out, we could update this: https://github.com/sol-eng/background-jobs/tree/main/shiny-job. 

I'm messing around with callr but woud more than welcome a solution if you have one.
