### ISSUE TITLE
"The model: `code-davinci-edit-001` does not exist"

### ISSUE THREAD

**Issue by ichsan2895** [MichelNivard/gptstudio#67]
```{r}
Sys.setenv(OPENAI_API_KEY = "<my_API>")

plot(cars)
```
then I block the text of `plot(cars)`, then go to **Addins** > **GPTStudio** > **Comment your code**

The result as shown in the terminal is..
```
Asking GPT for help...
! OpenAI API request failed [404].Error message: The model: `code-davinci-edit-001` does not exist
$error
$error$message
[1] "The model: `code-davinci-edit-001` does not exist"

$error$type
[1] "invalid_request_error"

$error$param
NULL

$error$code
[1] "model_not_found"

Inserting text from GPT...
```

My computer configuration:
```
R 4.2.3
gptstudio 0.1.0
RStudio 2023.03.0 Build 386
MXLinux 19.4 KDE based from Debian 10
```

**Comment by JamesHWade** [comment]
OpenAI discontinued that model. We'll have to update the code. Thanks for reporting!

**Comment by calderonsamuel** [comment]
This was a bug in the openai api and was fixed many days ago: https://community.openai.com/t/the-model-text-davinci-edit-001-does-not-exist/116144/28

**Comment by JamesHWade** [comment]
Thanks for sharing! Closing for now.
