### ISSUE TITLE
Error: 'card' is not an exported object from 'namespace:bslib'

### ISSUE THREAD

**Issue by yihualiued** [MichelNivard/gptstudio#68]
I am working on RStudio Workbench and was not able to lunch the addin with the following error:

```r
> gptstudio:::addin_chatgpt()
Loading required package: shiny
Error: 'card' is not an exported object from 'namespace:bslib'
```
It looks to me like it's a communication problem with bslib. I have updated gptstudio, bslib and shiny, but the problem still remains.

**Comment by JamesHWade** [comment]
What version of bslib do you have installed?  I'm looking for the output of `packageVersion("bslib")`. I use RStudio Workbench for work, so I can try to replicate.

**Comment by yihualiued** [comment]
Thank you @JamesHWade for your prompt reply. The version is 0.4.0
```r
> packageVersion("bslib")
[1] ‘0.4.0’
```

**Comment by JamesHWade** [comment]
Ah, that's it. The minimum version of 0.4.2. I'll add a check for that.

**Comment by yihualiued** [comment]
Aha, you are right! It's weird my previous updating didn't bring it to the latest version. Now it works. Thanks for the help

**Comment by JamesHWade** [comment]
Glad it's working now! Please open the issue back up if you still have issues.
