### ISSUE TITLE
error with intall gptstudio

### ISSUE THREAD

**Issue by Dave-stack** [MichelNivard/gptstudio#75]
Error in parse(outFile) : 
  C:/Users/Administrator/AppData/Local/Temp/Rtmp6jo3Hc/R.INSTALL9784bfb21b8/gptstudio/R/openai_api_calls.R:206:6: unexpected'>'
205:     )
206:   ) |>
          ^

According to the manual, I have tried installing it many times, but both failed. maybe the compilation failed with the pipe character.

 devtools::check()
  .....
 ERROR: unable to collate and parse R files for package 'gptstudio'
  ....
 Exited with status 1.

**Comment by JamesHWade** [comment]
Ah... used base pipe (`|>`) instead of magrittr (`%>%`). I'll change that.

**Comment by JamesHWade** [comment]
Should be fixed now.
