### ISSUE TITLE
app doesn't work in posit cloud

### ISSUE THREAD

**Issue by calderonsamuel** [MichelNivard/gptstudio#79]
There seems to be an issue in `open_bg_shinyapp()`. The translated URL sometimes works fine and sometimes opens an external browser with an unexpected URL that leads nowhere. This was tried multiple times in different blank posit cloud projects.

**Comment by idavydov** [comment]
I have issues with rstudio server. I often get connection refused. Maybe it's related to the time needed to load the shiny app?

What about adding this code after the `run_app_as_bg_job()` instead of `if (.Platform$OS.type == "unix") Sys.sleep(1.5)`?

```r
  # wait for the app to start
  start_time <- as.numeric(Sys.time())
  repeat {
    r <- tryCatch(
      httr::GET(glue::glue("http://{host}:{port}/")),
      error = \(e) NULL
    )
    if (
      as.numeric(Sys.time()) - start_time > 10 ||
        (!is.null(r) && httr::status_code(r) < 300)
    ) {
      break
    }
    Sys.sleep(0.2)
  }
```

That seems to solve the issue for rstudio server for me.

**Comment by calderonsamuel** [comment]
You spotted my very unrealiable bug fix for linux 🥲 . Your code looks like a much better aproach in handling the wait for the app starting time. However, the bug I found is different and it seems related to the URL translation. Allow me to explain it better.

In a new empty project when you have only installed `{gptstudio}` and setup your API KEY, the addin should open the app in the background and show it in the Viewer pane. The viewer needs a URL to show, and that URL must:

1. have a format accepted for the viewer pane (this error)
2. have content (otherwise you get the connection refused error).

When 1 is not respected the URL is opened in the system's browser. Here is how it goes with the chatgpt app:

https://user-images.githubusercontent.com/19418298/235739348-e42a5ebe-a54a-4ff2-8895-e0260779b951.mp4

The addin is still running in the background, but it is not possible to get a valid translated URL, even if you run the following code while the app runs in the jobs panel:

```r
url <- "http://127.0.0.1:<port>"
rstudioapi::viewer(rstudioapi::translateLocalUrl(url))
```

However, if you manually close the app and restart the R session, you can create a fake app wrapping the relevant app modules. This is to get the Run App button in Rstudio. With this, you can choose to run the app in the Viewer pane. After that it is possible to inspect the URL with the format that the Viewer pane accepts. 

https://user-images.githubusercontent.com/19418298/235744021-f3f068db-3012-42ab-9da3-45ab6bfbc2fb.mp4

I believe this is the format that `rstudioapi::translateLocalUrl()` should be returning but it doesn't for some reason. If this is a bug in `{rstudioapi}` we should warn the users. If this is a bug from this repo we should fix it. I'm also not sure in how to create an automated test for this.

**Comment by calderonsamuel** [comment]
There seems to be an unexpected manual fix for this. I don't know why this works but it does. After installation you need to relaunch the project. If you do this the addin runs with no problems. This is not the same as restarting the R session, I've tried that and it still fails if you don't relaunch the project.

You can see it in action here (in Youtube because it was too long for Github):

[![gptstudio - Posit cloud relaunch fix](https://img.youtube.com/vi/qUHchMU_vJg/0.jpg)](https://www.youtube.com/watch?v=qUHchMU_vJg)

Maybe `{gptstudio}` should warn about this on install?

**Comment by JamesHWade** [comment]
Your experience is similar to one I've seen on Posit Workbench. This might be an artifact of working on RStudio server environments in general. Best approach might be to get this issue in from of the team at Posit support Cloud and Workbench.

**Comment by calderonsamuel** [comment]
I'm thinking on closing this since downloading from CRAN works after restarting the R session (no longer requires to Relaunch project). @JamesHWade  Can you test on Posit Workbench to confirm? If not, we still can close this until someone reports on Posit Workbench.

**Comment by calderonsamuel** [comment]
Closing until someone reports something similar
