### ISSUE TITLE
Default settings for code style and skill level

### ISSUE THREAD

**Issue by awcm0n** [MichelNivard/gptstudio#83]
Is there a way to change the default settings for `gptstudio.code_style` and `gptstudio.skill`? Thanks!

**Comment by calderonsamuel** [comment]
The following should work for changing the skill level. You could do something similar for code style.

```r
options(gptstudio.skill = "advanced") # choose any value
```

This is valid until you close the current R session or overwrite the options.

 If you want to have it ser for all your projects you could explore using an `.Rprofile` file. Here is an in depth explanation: https://support.posit.co/hc/en-us/articles/360047157094-Managing-R-with-Rprofile-Renviron-Rprofile-site-Renviron-site-rsession-conf-and-repos-conf
