### ISSUE TITLE
Response in the chat app takes a very long time

### ISSUE THREAD

**Issue by calderonsamuel** [MichelNivard/gptstudio#85]
This is because the request waits for the whole response. The [chat completion endpoint ](https://platform.openai.com/docs/api-reference/chat/create#chat/create-stream) has an `stream` parameter that can allow to get deltas of the response, which also gives the typewriting effect for new messages.

The httr package (the current backbone of the requests) has a `write_stream()` function that maybe can be used for this. However, the httr2 package also has `req_stream()` function that looks very clean.

httr: https://httr.r-lib.org/reference/write_stream.html

httr2: https://httr2.r-lib.org/reference/req_stream.html

**Comment by JamesHWade** [comment]
This could be a good impetus for us to swap to httr2. I've been using it for other packages, and I like it a lot.

Two features in this one:

- [ ] Swap out httr with httr2
- [ ] Add streaming
