### ISSUE TITLE
FR: Custom system prompts for the chat app

### ISSUE THREAD

**Issue by calderonsamuel** [MichelNivard/gptstudio#86]
Although the main use for the RStudio IDE (home of the addin) is programming in R, the chat app could be used for all kinds of tasks. Having the option to set custom system prompts would help with this.

**Comment by JamesHWade** [comment]
An overhaul of our prompts in general would be a good idea. [DeepLearning.ai](https://deeplearning.ai) has a short course on prompt engineering I've found useful.

**Comment by JamesHWade** [comment]
Should be addressed with #122, but please re-open if it doesn't work as expected.
