### ISSUE TITLE
FR: Import and export chat history

### ISSUE THREAD

**Issue by calderonsamuel** [MichelNivard/gptstudio#87]
Users of the chat app can benefit from taking a look to older messages, just like they can do in the original ChatGPT. It would be nice to have an option to store the chat history. 

An interesting project that has already implemeted this in JS is [chatbot-ui](https://github.com/mckaywrigley/chatbot-ui). The chat app addin can benefit from using the same format to store the chat history.

**Comment by JamesHWade** [comment]
Great idea! I have part of that infrastructure already built out in jameshwade/gpttools, so we don't have to start from scratch.

**Comment by calderonsamuel** [comment]
Done with #153
