### ISSUE TITLE
add a function to set the URL of API KEY

### ISSUE THREAD

**Issue by distinerwjs** [MichelNivard/gptstudio#90]
I found that gptstudio can only set the API key, and we can only go to OpenAI to search for this key. Can we add a function to set the URL

**Comment by calderonsamuel** [comment]
Can you elaborate on what you mean by "set the URL"? 

My first guess is that you mean targetting a specific endpoint in the openai API. For that, a quicker option would be to use the [`openai`](https://irudnyts.github.io/openai/) package, which right now provides a wider range of options for HTTP requests. 

This package will have a rework of how it handles communication with the API with a main focus on chat completions. After that it might be possible to expand to other endpoints.

**Comment by distinerwjs** [comment]
As a user from China, we cannot use OpenAI's API normally, but API2D provides alternative methods and ways. So what I would like to inquire about is: Can you provide a configurable method to achieve this?

**Comment by calderonsamuel** [comment]
I understand better now. I need more information to try implementing this. I tried searching the API2D documentation but was unsuccessful (sadly, there is also a language barrier 😢). I need to know what the URL would look like. Currently, the package uses a base URL and an endpoint to retrieve the information.

```R
base_url <- "https://api.openai.com/v1"
endpoint <- "/chat/completions"
```

We do this to be able to target different endpoints with the same base request. How should we handle the API2D case? Specifically, how would a request for a chat completion look like? Please provide as much detail as possible and, if possible, include examples.

Are there other services that would benefit from these changes? Can we think of a general approach to handle this that would also be easy to maintain?

**Comment by jjccco** [comment]
> I also encounter this question as a user from China. Here is a third-party API provider rather than the official site [api.openai.com], so is there a solution I change the default [api.openai.com] to apply my API.

**Comment by jjccco** [comment]
> I understand better now. I need more information to try implementing this. I tried searching the API2D documentation but was unsuccessful (sadly, there is also a language barrier 😢). I need to know what the URL would look like. Currently, the package uses a base URL and an endpoint to retrieve the information.
> 
> ```r
> base_url <- "https://api.openai.com/v1"
> endpoint <- "/chat/completions"
> ```
> 
> We do this to be able to target different endpoints with the same base request. How should we handle the API2D case? Specifically, how would a request for a chat completion look like? Please provide as much detail as possible and, if possible, include examples.
> 
> Are there other services that would benefit from these changes? Can we think of a general approach to handle this that would also be easy to maintain?

as you said the base_url is "https://api.openai.com/v1", the third-party API provider requires users to change the API Base which is "https://api.openai-proxy.org" and I don't know how to do in this R package

**Comment by ltj-github** [comment]
I am a user from China. It is inconvenient to use the OpenAI website domestically. My API key is from a third party. I want to modify https://api.openai.com/ to https://api.chatanywhere.com.cn/. How can I proceed with this operation?

**Comment by JamesHWade** [comment]
#119
