### ISSUE TITLE
Missing 'write/code from prompt'

### ISSUE THREAD

**Issue by vincentoh698** [MichelNivard/gptstudio#92]
I've added the package but the 'write/code from prompt' option is nowhere to be found. How do I fix it?

**Comment by calderonsamuel** [comment]
I believe this was renamed to **ChatGPT in source**. Check [here](https://github.com/MichelNivard/gptstudio#provide-your-own-instructions-in-r-r-markdown-or-quarto-files)

**Comment by vincentoh698** [comment]
I see, thanks for the help! Appreciated.
